### ISSUE TITLE
reindex the dataframe

### ISSUE THREAD

**Issue by erictamhk** [data-forge/data-forge-ts#10]
i want to have a function that can reindex the dataframe
something like the pandas.DataFrame.reindex

**Comment by ashleydavis** [comment]
I'm not sure off the top of my head, I'll have to look up the Pandas reindex function to remember how it works. I'll get back to you in a couple of days.

Maybe you could describe to me the behavior you'd like to see in DataForge?

**Comment by erictamhk** [comment]
i implement this function by using javascript, i don't know am i do it right, but it work.
i find that the DataFrame.at() is very slow to get a row of data.

`dataForge.DataFrame.prototype.reindex = function(new_index, fill_value = null) {
  let newArray = ["tempIndex"].concat(this.getColumnNames());
  let pairs = this.toPairs();
  let newIndexArray = new_index.toArray();
  const dfIndexArray = this.getIndex().toArray();

  const filterPairs = pairs.reduce(function(a, e, i) {
    if (newIndexArray.indexOf(e[0]) >= 0) {
      let obj = e[1];
      let idx = e[0];
      let newObj = {};
      newArray.forEach(val => {
        if (val === "tempIndex") {
          newObj[val] = idx;
        } else {
          newObj[val] = obj[val];
        }
      });
      a.push(newObj);
    }
    return a;
  }, []);

  const emptyPairs = newIndexArray.reduce(function(a, e, i) {
    if (dfIndexArray.indexOf(e) === -1) {
      let newObj = {};
      newArray.forEach(val => {
        if (val === "tempIndex") {
          newObj[val] = e;
        } else {
          newObj[val] = fill_value;
        }
      });
      a.push(newObj);
    }
    return a;
  }, []);`

**Comment by ashleydavis** [comment]
Reindex won't make `at` any faster.

Currently `at` doesn't even use the index. I'll re-write the function at some point so that uses the index.

**Comment by shajeeck** [comment]
@ashleydavis as you mentioned `at` doesn't use index, what is the function which uses index to return the row?

**Comment by shajeeck** [comment]
@ashleydavis Or is it already rewritten as i can see in the docs? 
[https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#getting-a-row-or-value-by-index](url)

**Comment by ashleydavis** [comment]
The at function takes an index and returns the first value at that index.

The at function is not optimised, so it is quite slow (this can be fixed of course),
