### ISSUE TITLE
cumulative mean/median/mode etc...

### ISSUE THREAD

**Issue by nemosmithasf** [data-forge/data-forge-ts#109]
I see that data-forge has the `cumsum` function, but I don't see any equivalent for mean/median/mode etc...

I'm wondering if this simply isn't implemented or if there's a canonical way of working with cumulatives I'm not aware of.

For reference; this is the Zebras implementation to give context on what I mean:
https://zebrasjs.com/Z.html#.cumulative
https://zebrasjs.com/cumulative.js.html

**Comment by ashleydavis** [comment]
There is no version of that for mean/median/mode.

Please feel free to add what you need to Data-Forge and submit a pull request.

Otherwise in version 2 I'll be revising the status functionality and consider adding that.

**Comment by ashleydavis** [comment]
Oh by the way you could probably implement this fairly easily in terms of the `aggregate` function:

https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#aggregate

**Comment by nemosmithasf** [comment]
Alright, thanks for clarifying; and doubly thanks for your work on the library.

**Comment by ashleydavis** [comment]
Much obliged, thanks for your feedback.

Don't forget to star the code repository if you haven't already.
