### ISSUE TITLE
parseDates() formatting not working

### ISSUE THREAD

**Issue by tunneling** [data-forge/data-forge-ts#112]
I'm using the data-forge-ts library in an Angular project and I'm unable to get the date to convert to the desired format. I'm not sure if I'm doing something wrong or if there's an issue with the library.

A minimal example is here:

https://stackblitz.com/edit/date-sandbox-data-forge-ts?file=app/app.component.ts

The input date format is:

`"03/01/2021"`

This line of code:

`const df = idf.parseDates("date");`

results in a date that looks like:

`Mon Mar 01 2021 00:00:00 GMT-0600 (Central Standard Time)`

This line of code:

`const df = idf.parseDates("date", "YYYY-MM-DD");`

results in

`Invalid Date`

**Comment by ashleydavis** [comment]
Hi, thanks so much for reporting the issue and for your sponsorship.

I'll look into this soon and get back to you.

**Comment by ashleydavis** [comment]
So you probably want to do this instead:

```javascript
const df = idf.parseDates("date", "DD/MM/YYYY");
````

That function parses the dates from your source date format into JavaScript date objects.

Your example input date is "03/01/2021",  so it looks like your format is either "DD/MM/YYYY" or "MM/DD/YYYY".

Please let me know if this helps.

You might also want help displaying the dates in a particular format... so let me know if that's the case.

**Comment by ashleydavis** [comment]
Here's what your example looks like after I made the change:

![Uploading image.png…]()

**Comment by tunneling** [comment]
So it looks like that format string passes through daysjs, but the output is still 

`Mon Mar 01 2021 00:00:00 GMT-0600 (Central Standard Time)`

I was hoping to see the same format as the input date, but with it now typed as Date.

**Comment by tunneling** [comment]
That could be me misunderstanding the parameters.. is the format string a guideline to help daysjs interpret the input of the format string?

**Comment by ashleydavis** [comment]
Yeah that's basically it.

**Comment by ashleydavis** [comment]
These the valid parameters:

https://day.js.org/docs/en/display/format

**Comment by ashleydavis** [comment]
Sorry, it's more like this:

https://day.js.org/docs/en/parse/string-format

Very similar... but you can set the format for your source data (what you are doing) and you can also set the format for your output (which you might also want to do to make the dates display nicely).

**Comment by tunneling** [comment]
Thank you for your help. I'm more of a code by example type of guy.

So to format the date output, is there a function or an additional parameter to the parseDates() provided by data-forge-ts for that?

**Comment by ashleydavis** [comment]
Yeah there is if you want to convert your dates to formatted strings across the whole data frame you can do it like this:

```javascript
const formattedDF = df.toStrings("date", "DD/MM/YYYY"); // Use whatever format you want.
```

That will rewrite your dates for that column in the format you want.

Here's the docs for the toStrings function: 
https://data-forge.github.io/data-forge-ts/classes/dataframe.html#tostrings

Here's what your code might look like with the update:
![image](https://user-images.githubusercontent.com/625126/110061211-ef74ec00-7db2-11eb-95f5-4261f0e5502e.png)

**Comment by ashleydavis** [comment]
To be honest, though you may not even need to do anything your dates in the first place...

If you don't parse them in the first place they'll just come through in the original format, for example here's your code with parsing and formating of dates removed, it's simply passing the original format through:

![image](https://user-images.githubusercontent.com/625126/110061340-2d721000-7db3-11eb-88a8-0e762288e2e2.png)


Parsing your dates is only useful if you'd like to have them as JavaScript Date objects, where you can manipulate and trasform them. Say if you wanted to map your dates between time zones... if you just want to display the dates as they appear in your source data you can simply let them pass through with parsing or formatting.

**Comment by tunneling** [comment]
So in my real application, I'm acquiring a list of transactions from a nestjs backend and the date format is as it comes from MySQL (e.g. 2020-07-19). I'm trying to build an interface that can provide different views of the data. I'm hoping that I can use data-forge to manipulate the DataFrame to different formats. For example, the real data would have some value (e.g. dollars) as a series in the dataframe. I would like to manipulate the dataframe from a transaction list to a time table (with the dates as series). In addition, I would like to be able to change the resolution of the date series (e.g. daily, weekly, bi-weekly, etc.). I have no idea how to do any of that yet, but I was assuming my string dates need to be typed as dates.

**Comment by ashleydavis** [comment]
That's a good assumption. 

By the way thanks for providing the sample code, that makes it really easy to give help.
