### ISSUE TITLE
transposing series to rows using a dataframe object

### ISSUE THREAD

**Issue by tunneling** [data-forge/data-forge-ts#113]
Does data-forge-ts have built in functionality to transpose a dataframe? I feel like the `pivot` function is where I need to look, but not sure if I can achieve exactly what I'm trying to do.

I have a hardcoded example here:

https://stackblitz.com/edit/sandbox-data-forge-ts?file=app/app.component.html

In the original dataset, there is a series of dates and corresponding values. Essentially I would like to convert the dates to columns while aggregating the values on a particular "category" (i.e. another column name). _note, in the example, I hardcoded the transposition. Hopefully my math is right_

From:

(Click the Detail Button on above linked example)

![image](https://user-images.githubusercontent.com/4457051/110217133-0df0eb00-7e78-11eb-9540-de6e29538597.png)

To:

(Click the Timeline Button on above linked example)

![image](https://user-images.githubusercontent.com/4457051/110217607-92dd0400-7e7a-11eb-9769-348a241f32f4.png)

As an aside to this question, and this could be my limited js knowledge, can the column names (e.g. Total Hours, Min Hours, Max Hours) be replaced with variables in this snippet?

      var summarized = this.idf
        .groupBy(row => row[fieldName])
        .select(group => ({
          Discipline: group.first().discipline,
          "Total Hours": group.deflate(row => row.hours).sum(),
          "Min Hours": group.deflate(row => row.hours).min(),
          "Max Hours": group.deflate(row => row.hours).min()
        }))
        .inflate();

**Comment by ashleydavis** [comment]
Hey sorry, haven't had a chance to look at this yet. Crazy week so far. Will try and look tomorrow!

**Comment by ashleydavis** [comment]
So what you are doing there really is just long-hand for a pivot. That can be useful if you'd like to full customize the operation of the pivot function.

I haven't tested it but off the top of my head I think you could achieve the same like this:

```javascript
var columnToGroupBy = fieldName;
var summarized = this.idf.pivot(columnToGroupBy, {
      Discipline: Series.first,
      "Total Hours": Series.sum,
      "Min Hours": Series.min,
      "Max Hours": Series.max,
});
```

You can also structure "pivot spec" as variables like this:

```javascript
var summarized = this.idf.pivot(columnToGroupBy, {
      discipline: Series.first,
      totalHours: Series.sum,
      minHours: Series.min,
      maxHours: Series.max,
});
```

Pivot also does a sort though... so the output will be sorted by "columnToGroupBy" which might not be what you wanted.

Checkout the docs for pivot here:

https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#pivot

Note in the docs that you can also group on multiple levels of columns.

Does that answer your questions?

**Comment by tunneling** [comment]
yes, I think so. Thanks!
