### ISSUE TITLE
Drop Null/Undefined Rows Feature

### ISSUE THREAD

**Issue by leh08** [data-forge/data-forge-ts#115]
Hi @ashleydavis

Could we add a function dropNull(row/column) to data-forge? I think this function will be very useful

Regards
Giang

**Comment by ashleydavis** [comment]
When you extract a series from a dataframe it already does this, you can also do it using the `where` function to filter out rows that you don't want.

I'd be happy for you to contribute a new function to Data-Forge that does exactly what you need... maybe it should called `dropEmpty` though so it can drop both nulls and undefineds. What do you think?
