### ISSUE TITLE
Group dataset with different series

### ISSUE THREAD

**Issue by tunneling** [data-forge/data-forge-ts#116]
I have the following dataset:

```
    this.data = [
      { discipline: 1, originalBudgetDollars: 1114.96 },
      { discipline: 2, originalBudgetDollars: 192 },
      { discipline: 1, expendedDollars: 1137.24 },
      { discipline: 2, expendedDollars: 55.08 },
      { discipline: 1, forecastAtCompletionDollars: 1276.62 },
      { discipline: 2, forecastAtCompletionDollars: 96 },
      { discipline: 1, earnedValueDollars: 81.6 },
      { discipline: 2, earnedValueDollars: 10636.6 }
    ];
```

I would like to end up with the following dataset:

NOTE: the resulting dataset has a new column (remainingDollars) which is the difference between originalBudgetDollars and expendedDollars.

```
    this.data = [
      { discipline: 1, originalBudgetDollars: 1114.96, expendedDollars: 1137.24, remainingDollars: -22.28, forecastAtCompletionDollars: 1276.62, earnedValueDollars: 81.6 },
      { discipline: 2, originalBudgetDollars: 192, expendedDollars: 55.08,  remainingDollars: 136.92, forecastAtCompletionDollars: 96, earnedValueDollars: 10636.6 },
    ];
```

Is there a way to group on a series (e.g. discipline) while maintaining all of the unique series, and for icing on the cake.. add a new series which is the result of a function?

**Comment by ashleydavis** [comment]
You want `groupBy` and then collapse the groups however you want!

E.g.

```javascript
let df = new DataFrame(data);
df.groupBy(row => row.discipline)
     .select(group => {
        // Collapse the group however you like:
        return {
            discipline: group.first().discipline,
            summedColumn: group.getSeries("summedColumn").sum(),
            minColumn: group.getSeries("minColumn").min(),
            avgColumn: group.getSeries("avgColumn").average(),
            // ... and so on ...
        };
     })
     .inflate();
```

**Comment by ashleydavis** [comment]
Here's an example from the guide:

https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#group-and-aggregate

**Comment by tunneling** [comment]
Here's the function that returns the sorted array I needed:

      return new DataFrame(array)
      .groupBy((row) => row.discipline)
        .select((group) => {
          return {
            discipline: group.first().discipline,
            originalBudgetDollars: group.getSeries("originalBudgetDollars").sum(),
            expendedDollars: group.getSeries("expendedDollars").sum(),
            remainingDollars: (group.getSeries("originalBudgetDollars").sum() - group.getSeries("expendedDollars").sum()),
            earnedValueDollars: group.getSeries("earnedValueDollars").sum(),
          };
        })
        .inflate()
        .toArray()
        .sort((a, b) => (a.discipline > b.discipline) ? 1 : -1);

**Comment by ashleydavis** [comment]
Awesome.

Here's an improvement you can cache some of your sums:

```javascript
return new DataFrame(array)
  .groupBy((row) => row.discipline)
    .select((group) => {
      const originalBudgetDollars = group.getSeries("originalBudgetDollars").sum();
      const expendedDollars = group.getSeries("expendedDollars").sum();
      return {
        discipline: group.first().discipline,
        originalBudgetDollars: originalBudgetDollars,
        expendedDollars: ,
        remainingDollars: originalBudgetDollars - expendedDollars,
        earnedValueDollars: group.getSeries("earnedValueDollars").sum(),
      };
    })
    .inflate()
    .toArray()
    .sort((a, b) => (a.discipline > b.discipline) ? 1 : -1);
```

**Comment by ashleydavis** [comment]
Also, you might be able to do the sort using Data-Forge like this:

Awesome.

Here's an improvement you can cache some of your sums:

```javascript
return new DataFrame(array)
  .groupBy((row) => row.discipline)
    .select((group) => {
      const originalBudgetDollars = group.getSeries("originalBudgetDollars").sum();
      const expendedDollars = group.getSeries("expendedDollars").sum();
      return {
        discipline: group.first().discipline,
        originalBudgetDollars: originalBudgetDollars,
        expendedDollars: ,
        remainingDollars: originalBudgetDollars - expendedDollars,
        earnedValueDollars: group.getSeries("earnedValueDollars").sum(),
      };
    })
    .inflate()
    .orderBy(row => row.discipline)
    .toArray();
```

**Comment by tunneling** [comment]
Works like a charm! Thank you.

**Comment by tburd** [comment]
@ashleydavis, I was not able to find any example with dynamic object keys.
I tried to expand your code above and it worked quite well. Perhaps not the best way to it, but....  ;)

`
return new DataFrame(array)
  .groupBy((row) => row.discipline)
    .select((group) => {
          let allCols = {}
          // Known parameters
          allCols['identifier'] = group.first().identifier
          allCols['experiment'] = group.first().experiment
          allCols['sample'] = group.first().sample
          allCols['datetime'] = group.first().datetime
          // Unknown or "dynamic" parameters
          _.forEach(group.toArray(), function(value, key){
            allCols[value.parameter] = value.value
          })
          return allCols;
        })
    })
    .inflate()
    .orderBy(row => row.discipline)
    .toArray();
`

**Comment by ashleydavis** [comment]
@tburd I'm not really sure I understand what you are trying to achieve there!

One thing I can say is that you should cache the result of `first()` like this:

```javascript
return new DataFrame(array)
  .groupBy((row) => row.discipline)
    .select((group) => {
          let allCols = {}
          // Known parameters
          const first = group.first();
          allCols['parameter1'] = first.parameter1
          allCols['parameter2'] = first.parameter2
          allCols['parameter3'] = first.parameter3
          allCols['parameter4'] = first.parameter4
          // Unknown or "dynamic" parameters
          _.forEach(group.toArray(), function(value, key){
            allCols[value.parameter] = value.value
          })
          return allCols;
        })
    })
    .inflate()
    .orderBy(row => row.discipline)
    .toArray();
```

**Comment by ashleydavis** [comment]
Another thing is that you could dynamically generate `allCols` using `Object.entries`:

@tburd I'm not really sure I understand what you are trying to achieve there!

One thing I can say is that you should cache the result of `first()` like this:

```javascript
return new DataFrame(array)
  .groupBy((row) => row.discipline)
    .select((group) => {
          let allCols = {}
          // Known parameters
          const first = group.first();
          for (const [key, value] of Object.keys(first)) {
              allCols[key] = first[key];
          }
          // Unknown or "dynamic" parameters
          _.forEach(group.toArray(), function(value, key){
            allCols[value.parameter] = value.value
          })
          return allCols;
        })
    })
    .inflate()
    .orderBy(row => row.discipline)
    .toArray();
```
