### ISSUE TITLE
Add support for TSV

### ISSUE THREAD

**Issue by moltar** [data-forge/data-forge-ts#120]
I have a use case for working with TSV (tab separated values) files.

I think maybe a general solution would be to have a provider pattern that can then be pluggable and be able to deal with any source of data. 

Maybe v2?

**Comment by ashleydavis** [comment]
Hi @moltar thanks for your feedback!

Pluggable data sources are definitely intended for v2, but this wouldn't have to wait for that!

I think Papa Parse (which DF uses for CSV) also supports TSV. So it's possibly just a matter of turning it on.

All options for parsing are passed through to Papa Parse already, you might just to set the delimiter to the tab character.

Here are the Papa Parse options:

https://www.papaparse.com/docs#config

Please let me know if this makes it work for you.

**Comment by moltar** [comment]
Oh, yeah, great. Thanks. That will probably work!
