### ISSUE TITLE
Drop row by index

### ISSUE THREAD

**Issue by niklr** [data-forge/data-forge-ts#125]
Is it possible to drop/remove a single row from an existing DataFrame by its index?

**Comment by ashleydavis** [comment]
There isn't but it probably wouldn't be too difficult to add and I'm accepting PRs if you wanted to try writing the code for it.

**Comment by ashleydavis** [comment]
I've added a `remove` function to Data-Forge 1.9.4 that allows you to remove items from a DataFrame or Series by index
