### ISSUE TITLE
.at(i) not returning the correct row after sorting data frame

### ISSUE THREAD

**Issue by goleary** [data-forge/data-forge-ts#128]
After sorting a data frame, calling `df.first()` & `df.at(0)` return different results.

`df.first()` returns the correct row, that is after sorting.
`df.at(0)` returns the wrong row. It seems to be returning the 0th indexed row prior to sorting.

![image](https://user-images.githubusercontent.com/16123225/136734461-b7c99dfc-dfbf-4441-b3ff-6bda2378e9d2.png)

https://runkit.com/goleary/6163bf7f68b1e00009220b48

**Comment by L0v3l4c3** [comment]
I can confirm, and this is not only the case for sorting, it is also the case for other various utility functions.

From looking at the code, I saw this : 

```javascript
 private getRowByIndex(index: IndexT): ValueT | undefined {
        if (!this.indexedContent) {
            this.indexedContent = new Map<any, ValueT>();
            for (const pair of this.getContent().pairs) {
                this.indexedContent.set(pair[0], pair[1]);
            }
        }
       
        return this.indexedContent.get(index);
    }
```

getRowByIndex being the function used in the .at method. It seems like this.indexedContent is not being updated whenever we use mutating functions.

**Comment by ashleydavis** [comment]
I'm accepting PRs if someone wants to fix this issue.

**Comment by ashleydavis** [comment]
I just had a close look at this issue and there's actually no bug here, it's working the way it's intended.

Let me explain.

Here's the output of the dataframe before it is sorted, note that a default 0-based index has been automatically baked into the dataframe:

```bash
__index__  date  count
---------  ----  -----
0          14    1    
1          28    1    
2          13    1    
3          31    1    
4          15    3    
5          30    3    
```

Then after sorting the dataframe note that the same index is there but it has been put out of order by your sort:

```bash
__index__  date  count
---------  ----  -----
4          15    3    
5          30    3    
0          14    1    
1          28    1    
2          13    1    
3          31    1    
```

@goleary @L0v3l4c3 do you see how index 0 is associated with the value `{ date: 14, count: 1 }`.

This isn't a bug, once an index has been attached to each row in the dataframe it stays stuck to it. This makes a lot of sense when you think of the index being something else, say like a data/time.

You can get the behaviour you want by applying the function `resetIndex` after you have sorted the dataframe.

Here is an update to your code that adds `resetIndex` and makes it work the way you want it to:

```javascript
const dataforge = require('data-forge')

const df = new dataforge.DataFrame([
  { date: 14, count: 1 },
  { date: 28, count: 1 },
  { date: 13, count: 1 },
  { date: 31, count: 1 },
  { date: 15, count: 3 },
  { date: 30, count: 3 }
])
.orderByDescending(row=>row.count)
.resetIndex();

df.toArray();
```

**Comment by L0v3l4c3** [comment]
Great, thank you for the walkthrough.
