### ISSUE TITLE
Correct Dataframe .after documentation

### ISSUE THREAD

**Issue by antoyne7** [data-forge/data-forge-ts#134]
https://github.com/data-forge/data-forge-ts/blob/8db65080db48138f3733dc80222758bb5b2d0350/docs/classes/dataframe.html#L359-L365

`.before` should be `.after`

**Comment by ashleydavis** [comment]
Is this just a fix for the documentation?

Please submit a PR and I'll update it.

**Comment by ashleydavis** [comment]
Oh I just noticed you already has a PR. I've accepted it.

Thank you
