### ISSUE TITLE
'withSeries' of DataFrame not working correctly after filtering by 'where'

### ISSUE THREAD

**Issue by grigdevelop** [data-forge/data-forge-ts#139]
Code example

```
        const items = [
            { dur: -1 },
            { dur: 3 },
            { dur: 2 }
        ];
        const points = [ 1, 2 ];
        const df = new DataFrame(items);
        const newDf = df.where( row => row.dur > 0 ).withSeries( 'point', new Series( points ) );
        console.log( newDf.toArray() );
```

Expected result
```
[ { dur: 3, point: 1 }, { dur: 2, point: 2 } ]
```

Actual result
```
[ { dur: 3, point: 1 }, { dur: 2, point: undefined } ]
```

**Comment by ashleydavis** [comment]
This appears to be correct behaviour.

The `where` function retains the original index.

Here is the index for the original dataframe:

```
__index__  dur
---------  ---
0          -1
1          3
2          2
```

And here is the index for the filtered dataframe:

```
1          3
2          2
```

Here is the index for the series:

```
__index__  __value__
---------  ---------
0          1
1          2
```

You can see that the index for final the dataframe and the added series lines up perfectly:

```
__index__  dur  point
---------  ---  -----
1          3    2
2          2
```

The series provides no value for index `2` that is why `point` is `undefined` in that row.

Note: To get output like above use `dataframe.toString()` and `series.toString()`.
```

**Comment by ashleydavis** [comment]
If you really want to get the output you have requested you'll need reset the index for the filtered dataframe:

```javascript
const newDf = df.where(row => row.dur > 0).resetIndex().withSeries('point', new Series(points));
console.log(newDf.toString());
```

Then you will get the desired result:

```
__index__  dur  point
---------  ---  -----
0          3    1
1          2    2
```
