### ISSUE TITLE
What am I missing? (inconsistent math when generating a new column)

### ISSUE THREAD

**Issue by skwasha** [data-forge/data-forge-ts#142]
I have a dataframe with a column "strike". I try to generate a new column "strikeDiff" using generateSeries like so (the 739 number is just a placeholder for the moment):

```
const df2 = df
	.generateSeries({
		strikeDiff: (row) => Math.abs(row['strike'] - 739.0448),
	})
	.orderBy((row) => row.strikeDiff);
```
The resulting column sometimes has the correct result and other times is wildly off. For example:
```
"strike": 50,
"strikeDiff": 539.0448
```
vs.
```
"strike": 200,
 "strikeDiff": 539.0448
```
Any ideas what's going on here?

**Comment by ashleydavis** [comment]
I can't see anything obviously wrong with that snippet of code.

If you can give me some example code that demonstrates the problem I'll debug it and look deeper.

**Comment by skwasha** [comment]
Nvm - sorted it out. I should have been merging my intermediate DFs (I have to fetch each row individually) instead of concatenating them. I'm guessing something to do with index weirdness? Regardless, when I merge I see proper results.

**Comment by ashleydavis** [comment]
OK thanks for letting me know.
