### ISSUE TITLE
Console logs in construction DataFrame

### ISSUE THREAD

**Issue by omarelb** [data-forge/data-forge-ts#143]
Hi! I noticed that when constructing a DataFrame with the `columns` approach, I saw `22` in the console logs. To me, it seems like this side effect shouldn't be present when constructing a DataFrame, as it clutters up the logs.  I also saw `console.log("11");` a couple of lines above it.

https://github.com/data-forge/data-forge-ts/blob/6216c338006a6c211505bfc1d7441674bdf2a0ba/src/lib/dataframe.ts#L2899

**Comment by ashleydavis** [comment]
You are right, that shouldn't be there.

Feel free to submit a PR or I'll get it to it as soon as I can.

**Comment by omarelb** [comment]
Thanks for the reply :) I'll take a look!

**Comment by ashleydavis** [comment]
This is fixed now. The logging has been removed from v1.9.6. 

Thanks for letting me know.
