### ISSUE TITLE
Can data-forage-ts transpose index and columns?

### ISSUE THREAD

**Issue by ado5** [data-forge/data-forge-ts#151]
Can data-forage-ts transpose index and columns? 

such as pandas,

>d1 = {'col1': [1, 2], 'col2': [3, 4]}
>df1 = pd.DataFrame(data=d1)
>df1

result:
<table>
  <tr><th align="center"></th><th align="center">col1</th><th align="center">col2</th></tr>
  <tr><td>0</td><td>1</td><td>3</td></tr>
  <tr><td>1</td><td>2</td><td>4</td></tr>
</table>

> df1_transposed = df1.transpose()
> df1_transposed

result:
<table>
  <tr><th align="center"></th><th align="center">0</th><th align="center">1</th></tr>
  <tr><td>col1</td><td>1</td><td>2</td></tr>
  <tr><td>col2</td><td>3</td><td>4</td></tr>
</table>

I write some simple code here,
https://stackblitz.com/edit/typescript-trb1ym?file=index.ts

``` ts
import './style.css';
import { DataFrame, fromCSV, Series } from 'data-forge';

const csv =
  'StartDate,EndDate,Cnt\r\n2021-10-01,2021-10-31,17322\r\n2021-12-01,2021-12-31,15436\r\n2022-01-01,2022-01-31,17437\r\n2022-01-01,2022-01-31,12008\r\n2022-01-01,2022-01-31,17907\r\n2022-01-01,2022-01-31,21712\r\n2022-01-01,2022-01-31,13474\r\n2022-02-01,2022-02-28,17140\r\n2022-02-01,2022-02-28,11504\r\n2022-02-01,2022-02-28,17586\r\n2022-02-01,2022-02-28,20521\r\n2022-02-01,2022-02-28,12598\r\n2022-03-01,2022-03-31,16740\r\n2022-03-01,2022-03-31,12037\r\n2022-03-01,2022-03-31,17584\r\n2022-03-01,2022-03-31,12612\r\n2022-04-01,2022-04-30,16449\r\n2022-04-01,2022-04-30,12119\r\n2022-04-01,2022-04-30,12838\r\n2022-04-01,2022-04-30,18150\r\n2022-04-01,2022-04-30,20844\r\n2022-04-01,2022-04-30,12816\r\n2022-05-01,2022-05-31,16159\r\n2022-05-01,2022-05-31,11687\r\n2022-05-01,2022-05-31,12513\r\n2022-05-01,2022-05-31,16542\r\n2022-05-01,2022-05-31,20774\r\n2022-05-01,2022-05-31,12391\r\n';

const frame = fromCSV(csv);
const idxFrame = frame.parseInts('Cnt');
const pvFrame = idxFrame
  .pivot('StartDate', {
    Cnt: Series.sum,
  })
  .withIndex((row) => row.StartDate)
  .orderByDescending((row) => row.StartDate)
  .dropSeries('StartDate');

const appDiv: HTMLElement = document.getElementById('app');
appDiv.innerHTML = `<h1>TypeScript Starter</h1>`;
appDiv.innerHTML += pvFrame.toHTML();
```

it runs:
<table border="1" class="dataframe">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>Cnt</th>
       </tr>
    </thead>
    <tbody>
        <tr>
            <th>2022-05-01</th>
            <td>90066</td>
        </tr>
        <tr>
            <th>2022-04-01</th>
            <td>93216</td>
        </tr>
        <tr>
            <th>2022-03-01</th>
            <td>58973</td>
        </tr>
        <tr>
            <th>2022-02-01</th>
            <td>79349</td>
        </tr>
        <tr>
            <th>2022-01-01</th>
            <td>82538</td>
        </tr>
        <tr>
            <th>2021-12-01</th>
            <td>15436</td>
        </tr>
        <tr>
            <th>2021-10-01</th>
            <td>17322</td>
        </tr>
    </tbody>
</table>

how to make it:
<table border="1" class="dataframe">
    <tbody>
        <tr>
           <th></th>
            <th>2022-05-01</th>
            <th>2022-04-01</th>
            <th>2022-03-01</th>
            <th>2022-02-01</th>
            <th>2022-01-01</th>
            <th>2021-12-01</th>
            <th>2021-10-01</th>
      </tr>
      <tr>
           <td>Cnt</td>
            <td>90066</td>
            <td>93216</td>
            <td>58973</td>
            <td>79349</td>
            <td>82538</td>
            <td>15436</td>
            <td>17322</td>
        </tr>
    </tbody>
</table>

and how can I get the array :
[
     ['2022-05-01','2022-04-01','2022-03-01','2022-02-01','2022-02-01','2021-12-01','2021-10-01'],
     [90066,93216,58973,79349,82538,15436,17322 ]
]

could you help me?  thanks.

**Comment by ashleydavis** [comment]
There's no built in function to do that if there was it would be very expensive.

But here's some code that does what you want:

```javascript
import { DataFrame, fromCSV, Series } from 'data-forge';

const csv =
    'StartDate,EndDate,Cnt\r\n2021-10-01,2021-10-31,17322\r\n2021-12-01,2021-12-31,15436\r\n2022-01-01,2022-01-31,17437\r\n2022-01-01,2022-01-31,12008\r\n2022-01-01,2022-01-31,17907\r\n2022-01-01,2022-01-31,21712\r\n2022-01-01,2022-01-31,13474\r\n2022-02-01,2022-02-28,17140\r\n2022-02-01,2022-02-28,11504\r\n2022-02-01,2022-02-28,17586\r\n2022-02-01,2022-02-28,20521\r\n2022-02-01,2022-02-28,12598\r\n2022-03-01,2022-03-31,16740\r\n2022-03-01,2022-03-31,12037\r\n2022-03-01,2022-03-31,17584\r\n2022-03-01,2022-03-31,12612\r\n2022-04-01,2022-04-30,16449\r\n2022-04-01,2022-04-30,12119\r\n2022-04-01,2022-04-30,12838\r\n2022-04-01,2022-04-30,18150\r\n2022-04-01,2022-04-30,20844\r\n2022-04-01,2022-04-30,12816\r\n2022-05-01,2022-05-31,16159\r\n2022-05-01,2022-05-31,11687\r\n2022-05-01,2022-05-31,12513\r\n2022-05-01,2022-05-31,16542\r\n2022-05-01,2022-05-31,20774\r\n2022-05-01,2022-05-31,12391\r\n';

const frame = fromCSV(csv);
const idxFrame = frame.parseInts('Cnt');
const pvFrame = idxFrame
    .pivot('StartDate', {
        Cnt: Series.sum,
    })
    .withIndex((row) => row.StartDate)
    .orderByDescending((row) => row.StartDate);

const rows = [];
const headersField = "StartDate";
const fieldsToInclude = ["Cnt"];

for (const column of frame.subset(fieldsToInclude).getColumns()) {
    const row = [];
    row.push(column.name);
    for (const value of column.series) {
        row.push(value);
    }
    rows.push(row);
}

const transposedDf = new DataFrame({
        rows: rows,
        columnNames: ["Index"].concat(pvFrame.getSeries(headersField).toArray()),
    })
    .withIndex("Index")
    .dropSeries("Index");
console.log(transposedDf.toString());
```

I prototyped this code in Data-Forge Notebook:

![image](https://user-images.githubusercontent.com/625126/203464616-10495198-ec8a-417c-8afa-e4de0dd32db3.png)
