### ISSUE TITLE
Rollup support

### ISSUE THREAD

**Issue by laevilgenius** [data-forge/data-forge-ts#16]
Rollup generates a lot of `Circular dependency` warnings and produces a broken bundle with undefined variables.
Single-file bundle could probably resolve this issue.

**Comment by ashleydavis** [comment]
Yes! Single bundle is definitely on the horizon in the next couple of months.

Thanks for letting me know.

**Comment by ashleydavis** [comment]
I don't know about rollup, but this module works well with Browserify and Webpack.

I've now included a single bundle in the npm module under the directory /dist/web.

Please see "From the browser" instructions in [the readme](https://github.com/data-forge/data-forge-ts).

The repo also include webpack.node.config.js that you can use to bundle Data-Forge for use under Node.js.

**Comment by laevilgenius** [comment]
Web version works with rollup, but I have to replace `var dataForge` with `export const dataForge` to be able to import it properly. Could you bundle `esm` browser build as well?
Related issue: #33.

**Comment by ashleydavis** [comment]
If you know how to bundle for esm please do that and submit a PR.
