### ISSUE TITLE
getColumns(), getColumnNames(), hasSeries() don't see all columns if df is loaded fromJson()

### ISSUE THREAD

**Issue by syldman** [data-forge/data-forge-ts#165]
When a df loaded with fromJson() and json rows have varying keys, only persistent keys are seen in getColumns(), getColumnNames(), hasSeries() and expectSeries(). 

getSeries() sees the column and exports values. 'baking' doesn't seem to help

```
const {DataFrame} = require('data-forge');

const jsonData = [
{k1: 'v00', k2: 'v10'}, 
{k1: 'v01', k2: 'v11'}, 
{k1: 'v02', k2: 'v12', k3: 'v22',}]

const df = new DataFrame(jsonData)

console.log(df.getColumnNames())
// [ 'k1', 'k2' ]
console.log(df.hasSeries('k3'))
// false
console.log(df.getSeries('k3').toArray())
// [ 'v22' ]
console.log(df.getSeries('k3').distinct().count())
// 2
console.log(df.expectSeries('k3'))
//  throw new Error("Expected dataframe to contain series with column name: '" + columnName + "'.");
```

**Comment by syldman** [comment]
my bad

**Comment by ashleydavis** [comment]
Thanks so much for your feedback @syldman.

I have a simpler library now called Datakit that you might be interested to try out.
https://github.com/ashleydavis/datakit

I recorded a video demonstration of it the other night:
https://youtu.be/8yh5UPJrevY

If you have feedback on my new library that would be well appreciated!

**Comment by ashleydavis** [comment]
I got a fix published. It's in Data-Forge 1.10.1.

I ended up calling `toString` on each index value used in the `merge` function, that allows Date objects to be compared!

JavaScript is pretty weird sometime.

You can see the fix in this commit: https://github.com/data-forge/data-forge-ts/commit/7a061a8fae13b871722bc6df8ce986e5f202b89f

Please reopen this issue if the fix doesn't work for you.

**Comment by syldman** [comment]
Checked out Datakit. Looks neat!
