### ISSUE TITLE
generateSeries() on a df with duplicated index uses last row results for the given index value

### ISSUE THREAD

**Issue by syldman** [data-forge/data-forge-ts#168]
Hi Ashley. Just came across another bug. Generating series on a dataframe with non-unique index (e.g. multi-level pivot), for a given index replaces values with the last calculated for that index.

```
const {DataFrame, Series} = require('data-forge');

const jsonData = [ { i: 'A', y: 1 }, { i: 'A', y: 2 }, { i: 'A', y: 3 },]

const df = new DataFrame({values: jsonData}).setIndex('i')
console.log(df.toPairs())

const dfG = df.generateSeries({calculatedValue: row => row.y ** 2})
console.log(dfG.toPairs())

/*
wrong
[
  [ 'A', { i: 'A', y: 1, calculatedValue: 9 } ],  <== 1*1 = 1 got replaced with 9 from the last row for index === A,
  [ 'A', { i: 'A', y: 2, calculatedValue: 9 } ],  <== 2*2 = 4 got replaced with 9 from the last row for index === A,
  [ 'A', { i: 'A', y: 3, calculatedValue: 9 } ]
]

should be
[
  [ 'A', { i: 'A', y: 1, calculatedValue: 1 } ],
  [ 'A', { i: 'A', y: 2, calculatedValue: 4 } ],
  [ 'A', { i: 'A', y: 3, calculatedValue: 9 } ]
]
*/
```

**Comment by ashleydavis** [comment]
This is something to do with the index.

If you change this line of code :

```javascript
const df = new DataFrame({values: jsonData}).setIndex('i')
```

To remove the index:

```javascript
const df = new DataFrame({values: jsonData})
````

**Comment by ashleydavis** [comment]
This might seem strange but this is the way `generateSeries` is supposed to work. The behaviour actually derives from the implementation of `withSeries` (which is called by `generateSeries`).

`withSeries` attempts to add a new series to a dataframe by matching up indicies. This way you can index your dataframe by date and then added in a new sparse series of values at various dates and those values will be correctly aligned to the correct rows in the dataframe.

In your example you are assigning the value `9` (the last value calculated) to index `A` which is then replicated across all rows that have that index.

Thanks for your code example though! I added it as a failing test and debugged the DF code to find that it was designed this way (given that I started this project over 5 years ago I can't always remember how it's supposed to work ;) )
