### ISSUE TITLE
fromCSV : TypeError: row.map is not a function

### ISSUE THREAD

**Issue by alankrantas** [data-forge/data-forge-ts#169]
While calling `fromCSV` to parse a CSV-format string, I get the error message `TypeError: row.map is not a function`. The origin is possibly here:

https://github.com/data-forge/data-forge-ts/blob/master/src/index.ts#L154

I ended up having to install Papa Parse separately, parse the CSV to JSON first then dump it into a Dataframe.

**Comment by ashleydavis** [comment]
Hey @alankrantas thanks for your bug report.

Do you have an example of code and data that reproduces the TypeError?

Thanks so much.

**Comment by alankrantas** [comment]
Well...I test this in Node and it works find.

The issue is actually complicated. We're using a special Deno runtime running on cloud, which executes JS scripts bundled by Rollup from local environments.
