### ISSUE TITLE
Cost of assertions

### ISSUE THREAD

**Issue by robertmollitor** [data-forge/data-forge-ts#17]
Can the library have a way of optimizing (or disabling) chai assertions throughout dataframe and series?

I did some browser (Chrome) profiling and the assertions seemed to be a major factor, so I did some timings.

I can't give you a standalone example, but for basic context my two cases were

  [1] a 5000 row table that is aggregated down to about 200 rows: (30ms to parse, 200ms to aggregate),
  and [2] a wider 2000 row table that is aggregated down twice: (200ms to parse, 600 ms to aggregate).

After adding the following code to my start up (only change):

```
  import _ from "lodash";
  import { assert } from "chai";

  const chaiIsFunction = assert.isFunction;
  const chaiIsArray = assert.isArray;
  const chaiIsNumber = assert.isNumber;
  const chaiIsString = assert.isString;
  const chaiIsObject = assert.isObject;

  assert.isFunction = (o, msg) => { if (!_.isFunction(o)) chaiIsFunction(o, msg); };
  assert.isArray = (o, msg) => { if (!_.isArray(o)) chaiIsArray(o, msg); };
  assert.isNumber = (o, msg) => { if (!_.isNumber(o)) chaiIsNumber(o, msg); };
  assert.isString = (o, msg) => { if (!_.isString(o)) chaiIsString(o, msg); };
  assert.isObject = (o, msg) => { if (!_.isObject(o)) chaiIsObject(o, msg); };
```

the timings went down to [1] (30ms to parse, 80ms to aggregate) and [2] (200ms to parse, 190ms to aggregate).

(By the way, these second timings didn't really improve if I completely disabled the assertions with
```
    assert.isFunction = () => undefined;
    assert.isArray = () => undefined;
    assert.isNumber = () => undefined;
    assert.isString = () => undefined;
    assert.isObject = () => undefined;
```
)

My tests were done in a development build, so maybe this isn't as much of a factor in production, but chai seems like a
library designed for testing and not necessarily for production performance (at least I can't see any mention of a
particular production mode in their docs).

Thanks.

**Comment by ashleydavis** [comment]
You are right! The assertions are expensive and I'd like to remove them from the production build.

I need a build script that can remove the asserts before publishing to npm. I also plan to bundle all the code for fast loading.

I'm not sure when I'd get to this though. If you have a proposal for how to bring it online please let me know. Maybe you can help me implement it?

**Comment by robertmollitor** [comment]
I have a patch that replaces chai asserts with lodash checks in the non-test code.  All tests pass.

**Comment by robertmollitor** [comment]
Here's the pull request:

  https://github.com/data-forge/data-forge-ts/pull/18

**Comment by ashleydavis** [comment]
Pull request approved and published to npm. @robertmollitor  does that fix your issue?

**Comment by robertmollitor** [comment]
Works great.  Thanks!  Your library has been very reliable and fast for us.

**Comment by ashleydavis** [comment]
Awesome. Don't forget to star the repo (if you haven't already).

Also you might be interested in Data-Forge Notebook, my product for data analysis and viz in JavaScript: http://www.data-forge-notebook.com/
