### ISSUE TITLE
Streaming Dataframes

### ISSUE THREAD

**Issue by jfloodnet** [data-forge/data-forge-ts#173]
I have a app that subscribes to streams of prices. I'm looking for a suitable library to handle wrangling the streams. New events will come in frequently. 

How does data-forge perform for high frequency appends? Is this something I should consider or look elsewhere?

Thanks 🙏

**Comment by ashleydavis** [comment]
HI @jfloodnet, Data-forge is usually best when you have the whole data set in memory at the point where you want to use it.

Of course you could use it, by appending new records to a JavaScript array then using DF to analyse the entire set.  But it hasn't been optimized for that kind of usage so I'm not sure what the performance would be like. 

If you do decide to try it out, please let me know how it performs.
