### ISSUE TITLE
Resample data based on time resolution

### ISSUE THREAD

**Issue by leefsmp** [data-forge/data-forge-ts#175]
It's not clear to me how to use the lib in order to resample a dataset based on given time resolution, hopefully you can give me some help on that.

I have a dataset that may look like this 
```
[
    {timestamp: 1734048000000, value: 0.102}, 
     ...,  
    {timestamp: 1734393600000, value: 0}
]
```
 
I would like to create a API that can query that dataset based on given resolution: `day/hour/minute/second`.

If resolution is day, I would consider data newer than 7 days, if hours newer than 24h, if minute newer than 1 hour and second newer than 1minute.

Then I would like to return resampled data array of size 10 or 20 for instance, the values in each sample would need to be averaged based on nearest values in the dataset.

Hope that makes sense. Thanks

**Comment by ashleydavis** [comment]
@leefsmp Data-Forge has no support for resampling yet. That would be a cool feature though. Is it something you would be interested in working on?

**Comment by leefsmp** [comment]
Thanks for the proposition, but I'm afraid I do not have time and skills to land such an advanced feature.
