### ISSUE TITLE
Can we add and multiply in the series？

### ISSUE THREAD

**Issue by ColorWork** [data-forge/data-forge-ts#19]
want the math function of add and multiply and other operations of the data frame like python pandas

**Comment by ashleydavis** [comment]
You can probably do that already using the aggregate function.

But I'm open to new functions like that. Can give me some example code or pseudo-code that demonstrates how it might work in Data-Forge?

**Comment by ashleydavis** [comment]
Is this still something that you want to work on or shall I close this issue?

**Comment by ColorWork** [comment]
YES, you can close this issue
