### ISSUE TITLE
How to get equivalent of pandas.DataFrame.pivot_table

### ISSUE THREAD

**Issue by pikhovkin** [data-forge/data-forge-ts#2]
How to get equivalent of pandas.DataFrame.pivot_table like [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot_table.html#pandas.DataFrame.pivot_table)

`table = pivot_table(df, values=['D', 'E'], index=['A', 'C'],  aggfunc={'D': np.mean,  'E': [min, max, np.mean]})`

Output:
```
                  D   E
               mean max median min
A   C
bar large  5.500000  16   14.5  13
    small  5.500000  15   14.5  14
foo large  2.000000  10    9.5   9
    small  2.333333  12   11.0   8
```

**Comment by ashleydavis** [comment]
I've actually just updated the pivot function to be more like pandas, but it's not quite finished.

So you can only pivot on a single value, so you can't do that, the closest you'll get at the moment is something like this:

const df2 = df1.pivot(["A", "C"], "D", values => values.mean());

You could probably do two pivots (one for each value column) then merge the results using one of the `join` functions.

Ultimately it would be better if the Data-Forge pivot function acted completely like the Pandas function, so I'll keep this issue open until I deal with it properly.

You can find some examples of the existing pivot function here (scroll the end and work backwards through the examples):

https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example.test.ts

These examples are based on this blog:

 https://chrisalbon.com/python/data_wrangling/pandas_pivot_tables/

**Comment by ashleydavis** [comment]
Hi, just to let you know I've upgraded the Data-Forge pivot function to support multiple outputs so that you can use it more like Pandas.

So you now with Data-Forge 1.0.9 you can do your pivot like this:

```
const df2 = df1.pivot(["A", "C"], { 
    D: values => values.average(), 
    E: {
        min: values => values.min(),
        max: values => values.max(),
        mean: values => values.average()
    }
});
```

For an example please see the unit test _pivot can produce multiple output values_ in 
this file [pivot tests file](https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example.test.ts).

You also asked for multi-level indexes and columns (like Pandas), but at the moment I'm not planning on implementing this feature for Data-Forge. I'm afraid it's going to stay in the too-hard basket for the forseeable future.

**Comment by pikhovkin** [comment]
Awesome!

**Comment by ashleydavis** [comment]
Please star the repo!

**Comment by pikhovkin** [comment]
Long ago

**Comment by ashleydavis** [comment]
Great!

You might also be interested know that I'm writing a book on this type of thing.

Please take a look: http://bit.ly/2t2cJu2

**Comment by ashleydavis** [comment]
Hey Sergey,

Just wondering if you've seen my new library yet?

It's called Data-Forge Plot and integrates plotting/charting with Data-Forge.

Please check out [my blog post on it](http://www.the-data-wrangler.com/introducing-data-forge-plot/).

It's early days yet, but I'm trying to collect feedback on it.

**Comment by pikhovkin** [comment]
Looks interesting. Looks like a [plotly.js](https://github.com/plotly/plotly.js/)

**Comment by ashleydavis** [comment]
Cheers, thanks for pointing that out. Plotly is a paid product isn't it?

**Comment by pikhovkin** [comment]
[plotly.js under MIT license](https://github.com/plotly/plotly.js/#copyright-and-license)
