### ISSUE TITLE
initColumnNames function problem

### ISSUE THREAD

**Issue by cemayan** [data-forge/data-forge-ts#23]
I have an array of the same column names. (* actually different)
Example : city and CITY

_DataFrame.initColumnNames_ function recognizes these two as the same. (reason **toLowerCase()** method )
Result :  **city.1** and **CITY.2** 

 When i replace `return outputColumnNames;`   with  `return inputColumnNames;` , it works.

It would be nice, if it was presented as an option .

Do you have any other suggestions for this ? 

Thanks in advance.

**Comment by ashleydavis** [comment]
Hi thanks for you feedback, but I'm not really sure what you are talking about.

Can you please provide example code in GitHub or a Gist so I can see the problem.

**Comment by cemayan** [comment]
```
let colnames = ['city','CITY',...]    
let df = fromCSV('somestring' , {columnNames: colnames})  
let columnNames = df.getColumnNames() -> ['city.1', 'CITY.2' , ...] 
```
Then,
I want to  **CITY** column, but it comes empty array. 

`current_df.getSeries("CITY") -> [] `

I'm aware of column names a little strange  😃

**Comment by ashleydavis** [comment]
Please provide code in a runnable format (eg a GitHub repo) and I'll be happy to take a look at it!

**Comment by ashleydavis** [comment]
I'm closing this issue due to no response.
