### ISSUE TITLE
Getting a row by index quite slow

### ISSUE THREAD

**Issue by shajeeck** [data-forge/data-forge-ts#24]
Thanks for this awesome DataFrame library for nodejs, much wanted!

Indexing and using `at` function is quite slow with large DataFrames . `at` looks like very useful in terms of improving performance. Any workaround until `at` is fixed for its real intention? A fix will be much helpful if possible. Sorry that i am not aware of the internal working of a DataFrame for a PR

**Comment by ashleydavis** [comment]
Sorry there's no timeframe on that. Please feel free to fix it and submit a PR. I need more people to work on this project!

**Comment by shajeeck** [comment]
respect your time, hope some one with proper understanding on DataFrame and data-forge will contribute

**Comment by ashleydavis** [comment]
Performance of the at function has been improved in version 1.8.6.
