### ISSUE TITLE
TransformSeries by condition

### ISSUE THREAD

**Issue by gianfa** [data-forge/data-forge-ts#28]
Hi Ashley,
I'd like to propose you to implement a transformSeries by condition for DataFrame, to locally change column values in rows respecting the specific condition. 

I'd like to contribute, but I still don't know TS, anyway here is an example I wrote for personal use:
[transformSeriesByCondition](https://gist.github.com/gianfa/c7131fa9fe05200e45c5b9151c0c6ca4)
I hope it will be useful as it's been to me!
😊

**Comment by ashleydavis** [comment]
Thanks for sharing that! It's really cool to see how people are using Data-Forge.

Have you seen the `pivot` function? It might already be able to do what you want.

Look here for some examples:

https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example.test.ts
https://github.com/data-forge/data-forge-ts/blob/master/src/test/dataframe.pivot-example2.test.ts

**Comment by ashleydavis** [comment]
Don't forget to start the repo! ;)
