### ISSUE TITLE
Include browser version in distribution

### ISSUE THREAD

**Issue by JBatUN** [data-forge/data-forge-ts#29]
Would be helpful if you could include browser version (for include in script tag) for convenience.  Thanks for your consideration.  Nice Work!!!

**Comment by ashleydavis** [comment]
Yes I should do that! But you can easily bundle your own using Browserify or Webpack.

**Comment by JBatUN** [comment]
Used Browserify-as-a-service (https://wzrd.in/) and it worked without issue.  Thanks.

**Comment by ashleydavis** [comment]
Sorry I mean to tell you, last week I included in the npm module a version of Data-Forge pre-bundled for use in the browser.

I've added some docs for you. Check [the readme](https://github.com/data-forge/data-forge-ts/blob/master/README.md) and [the guide](https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#browser-installation-and-setup).

Let me know if you need any more help!

Please star this repo!
