### ISSUE TITLE
Getting data out of a dataframe can be slow (toArray, toPairs, etc)

### ISSUE THREAD

**Issue by cberthiaume** [data-forge/data-forge-ts#30]
Hi, this is related to https://github.com/data-forge/data-forge-ts/issues/11. I'm opening a new issue since I don't have permission to reopen the previous one and I'm not sure if the issue is in `toPairs` or the use of `fillGaps` and `rollingWindow`. The issue is very slow performance with from `toPairs`. Copying from my [comment](https://github.com/data-forge/data-forge-ts/issues/11#issuecomment-472115114) in the other issue.

I just pushed up a change to our [test repo](https://github.com/data-forge/data-forge-performance-test-issue-11). The changes are:

1. Update package.json to use the most recent version of data-forge
1. Slightly change the reported timings to make it more clear where the performance issue happens. Specifically, the slow down looks like it's coming out of the call to `toPairs()`.

The tests I'm looking at are method-1.js and method-2.js. The only difference between them is:
```
$ diff method-1.js method-2.js
76c76
< const mySeries = dfWithoutGaps.getSeries('value');
---
> const mySeries = new dataForge.Series(dfWithoutGaps.getSeries('value').toArray());
```

Output from running the tests:
```
cberthiaume@slow-lane:~/data-forge-performance-test-issue-11$ node method-1.js
Time to require: 980.9740000000002
Time to create DataFrame and getSeries: 8.874000000000024
Time for rolling window: 0.08599999999978536
Time for toPairs: 2067.8320000000003
cberthiaume@slow-lane:~/data-forge-performance-test-issue-11$ node method-2.js
Time to require: 975.4
Time to create DataFrame and getSeries: 63.06100000000015
Time for rolling window: 0.10500000000001819
Time for toPairs: 17.16599999999994
cberthiaume@slow-lane:~/data-forge-performance-test-issue-11$
```
The key difference is the huge difference in time to call `toPairs()`. Our use case requires us to call `toPairs()` and the only way to get acceptable performance when doing that is to recreate the series as you see in the diff above. However, our needs have changed that the slow down required to implement this workaround is becoming a bottleneck. Is there a a better way to get good performance from `toPairs()` without using this workaround? Should I open a separate ticket to track this?

Thanks again for all your help.

**Comment by ashleydavis** [comment]
Thanks for continuing to give feedback. I'll look at this soon.

**Comment by ashleydavis** [comment]
You can also add a call to `bake` to method-1.js and it will be very fast.

Replace:

```javascript
const mySeries = dfWithoutGaps.getSeries('value');
```

With:

```javascript
const mySeries = dfWithoutGaps.getSeries('value').bake();
```

Output:

```
> node method-1.js
Time to require: 695.795171
Time to create DataFrame and getSeries: 90.44877699999995
Time for rolling window: 0.10332499999992706
Time for toPairs: 8.236728999999968
```

**Comment by ashleydavis** [comment]
It makes me think this is a problem that can be fixed by adding caching to Data-Forge and cache computations that are reused.

**Comment by ashleydavis** [comment]
Otherwise I could potentially put the call to `bake` inside the `rollingWindow` function.

**Comment by ashleydavis** [comment]
The real problem is that for each window it re-evaluates the the input datafame way too many times.

I think this can be solve in DataFrameRollingWindowIterator and SeriesRollingWindowIterator by making sure that the same rows/values are not visited multiple times.

Although curiously the `window` function suffers a similar performance issue, but from what I can see it doesn't revisit any values.

**Comment by ashleydavis** [comment]
Ok I've made an update that I believe significantly improves performance in the test case (although still not quite perfect).

@cberthiaume can you please try method-1 with Data-Forge 1.6.2 and confirm if the change helps performance?

If it does help I'll replicate  the change across several other functions where it should also help.

**Comment by cberthiaume** [comment]
@ashleydavis, thanks so much for looking into it.

Version 1.4.7:
```
Time to require: 850.4708919999999
Time to create DataFrame and getSeries: 6.12524499999995
Time for rolling window: 0.06310000000007676
Time for toPairs: 1967.1751649999999
```

Version 1.6.2:
```
Time to require: 849.6046000000001
Time to create DataFrame and getSeries: 6.100916999999981
Time for rolling window: 0.06195999999999913
Time for toPairs: 860.3463960000001
```
The performance at 1.6.2 is significantly faster though still quite a bit slower in total time as compared to method 2. Nice work! I'll try out the `bake` call in a bit and see how that performs.

**Comment by ashleydavis** [comment]
That's great. I'll continue to find new ways to improve performance.

**Comment by ashleydavis** [comment]
I've published another improvement and I'm wondering if it makes much difference for you.

I've experimented with bundling DF using webpack to see if it improves the time to require.

To try this out for yourself please install Data-Forge 1.6.4 and replaced this:

```javascript
const dataForge = require('data-forge');
```

With this:

```javascript
const dataForge = require('data-forge/dist/node');
```

My timings show probably not enough improvement to be worthwhile. But please let me know your results and if you think it's a worthwhile performance improvement.

**Comment by cberthiaume** [comment]
I tried it out and if anything it was slightly slower over a few runs. They were all within typical variance to 1.6.2 though.

**Comment by cberthiaume** [comment]
Well, the `Time to require` timing might be slightly faster. Maybe 30-40ms. The `Time for toPairs` is the same speed though.

**Comment by ashleydavis** [comment]
I'm still working on it ;) 

I just thought I'd try the bundling because I was looking at that for the browser version of Data-Forge anyway and I though it might improve the require time, but it doesn't seem to be a good enough improvement by itself.

**Comment by cberthiaume** [comment]
Right on. I did experiment with `bake()` and the net performance is still better by quite a bit in our app using the strategy in method-2. That's a good tip though, I didn't know about `bake()` and I can see it being useful in a different scenario.

**Comment by ashleydavis** [comment]
Try it again now with Data-Forge 1.6.5. I've done a few more performance tweaks. I've measured the whole operation (not including require time) and it comes in at 20-30 milliseconds without any bakes. 

Please remove any bakes from your code and try it again and let me know if you can replicate my results.

**Comment by cberthiaume** [comment]
Awesome, that's way faster!

1.6.5:
```
Time to require: 852.7489479999999
Time to create DataFrame and getSeries: 5.530737999999928
Time for rolling window: 0.11441600000011931
Time for toPairs: 20.120862999999872
```
It still looks like the method-2 approach is quicker overall though. Here is the method 2 times for 1.6.5:
```
Time to require: 842.570109
Time to create DataFrame and getSeries: 13.88006200000018
Time for rolling window: 0.07640399999991132
Time for toPairs: 2.456711999999925
```
And bumping the data set size up to 1000 from 100 gives us these.

method-1:
```
Time to require: 841.305452
Time to create DataFrame and getSeries: 22.755089999999882
Time for rolling window: 0.12125800000012532
Time for toPairs: 154.13425499999994
```

method-2:
```
Time to require: 966.312294
Time to create DataFrame and getSeries: 74.31753400000002
Time for rolling window: 0.08286599999996724
Time for toPairs: 20.17217800000003
```
Getting much closer!

**Comment by cberthiaume** [comment]
Also, I haven't had time to recreate it in the test repo but in our application method-1, even at 1.6.5, still hangs the browser for a long time. I end up having to kill the tab after tens of seconds to minutes depending on how patient I am. In our case, we are doing something like this:

```js
// this.fillActivityGaps returns a dataframe with roughly 400 rows and 20+ columns
const df = new dataForge.DataFrame(this.fillActivityGaps(activities, false).toArray());
      const columnA = df.getSeries('columnA');
      const columnB = df.getSeries('columnB');
      const columnC = df.getSeries('columnC');
      const columnD = df.getSeries('columnD');

columnD .rollingWindow(28)
        .select((window) => {
          // ...
        })
        .toPairs()
        .map((pair) => {
          // ...
          // calls columnA.at(), columnB.at(), columnC.at()
        });
```
Seems like there could be a combination of things impacting this.

1. The issue you're working on here
1. The `at()` calls as discussed here: https://github.com/data-forge/data-forge-ts/issues/24
1. Our code might be structured poorly

Thanks again for all your help. I might be able to put together an example that mimics what we're doing in our app more fully over the next few days if you're interested.

**Comment by ashleydavis** [comment]
The at function can be vastly improved!

Are you able to give me a separate meaningful performance test for that?

**Comment by ashleydavis** [comment]
You can put the new performance test in the same repo, just make a different file for it.

**Comment by ashleydavis** [comment]
Also it occurred to me that there is something you may not realize... the Data-Forge API is lazily evaluated. So most of the functions (eg `rollingWindow`) don't actually do anything, they kind of just queue up commands. It's only when you call a function that forces evaluation, such as `toArray` or `toPairs` that the whole chain of commands is actually evaluated. So that's why it seems like those functions are expensive.

Now one thing that makes it expensive is that there is not yet any internal caching, so that means if you call `toArray` followed by `toPairs` (or any other sequence of calls that forces evaluation) then you are going to pay the evaluation cost multiple times. Using a call to `bake` mitigates this by forcing an evaluation, you can then cache the resulting 'baked' dataframe and use it for multiple calls to `toArray`, `toPairs` and the like.

At some soon I'd like to support internal caching and that should make use of `bake` unnecessary in most cases. I'm still try to decide how to implement caching though. One of my goals for Data-Forge was to minimize the behind the scenes magic (like caching) - but maybe that's a goal that's no longer relevant anyway.

**Comment by ashleydavis** [comment]
Hey @cberthiaume I'm closing this now.

If you have another performance problem I'll be happy to look at it, you'll need to submit a new issue and some example code.

**Comment by tonyxiao** [comment]
On a related note, is there any reason why `toArray` is creating an entirely new array, rather than returning the existing pointer, when the content is already baked?

**Comment by ashleydavis** [comment]
Probably because it's going through a JavaScript iterator.
