### ISSUE TITLE
Transforming JS object to CSV

### ISSUE THREAD

**Issue by cowchimp** [data-forge/data-forge-ts#31]
Hi.

With the split to `data-forge` and `data-forge-fs`, I'm not sure how to turn an array of JS Objects I have in memory into a CSV file.

`fromObject()` is defined on `data-forge` but `asCSV()` and `writeFileSync()` are defined in `data-forge-fs`.

Example data structure
```js
const arr = [
  { first: 'micky', last: 'mouse' },
  { first: 'minnie', last: 'mouse' }
];
// How do I turn `arr` into a CSV file?
// Do i import `data-forge` or `data-forge-fs` or both?
```

Thank you.

**Comment by ashleydavis** [comment]
After the split you need to include both `data-forge` and `data-forge-fs`. That's it, that's all you have to do differently:

```javascript
const dataForge = require("data-forge");
require("data-forge-fs");

// You code goes here
```

You can read more about how to do this in [The Guide](https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#working-with-json-files).

Please let me know if any part of it isn't clear.
