### ISSUE TITLE
Transform Wide-to-Long and Long-to-Wide

### ISSUE THREAD

**Issue by JBatUN** [data-forge/data-forge-ts#32]
A feature request for consideration ... including transforms for wide-to-long and long-to-wide data structures.  For example:  https://sejdemyr.github.io/r-tutorials/basics/wide-and-long/

Thanks for considering.

**Comment by ashleydavis** [comment]
Thanks for the link that looks like a really interest post.

You might already be able to do this using [the pivot](https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#pivot) function?

Please let me know if you find a way to do it.

**Comment by tonyxiao** [comment]
I'm looking for a similar thing - transpose. Basically turning columns into rows and rows into columns.

**Comment by tonyxiao** [comment]
The use case is to display a table of transaction sums by month and category. Essentially columns needs to be computed based on values in the dataset.

**Comment by ashleydavis** [comment]
I'm sure you can do this already. 

Check out the summarize function: https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#summarize

Also the pivot function: https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#pivot

If these don't do what you want maybe you can provide an example of what the input and output look like? Then I could figure out how to achieve what you want.

**Comment by tonyxiao** [comment]
I was able to achieve it with Series.inflate cc @JBatUN

**Comment by ashleydavis** [comment]
Awesome. Can you submit some example code in a GitHub Gist? I'd love to see how you are using it.

**Comment by tonyxiao** [comment]
ah it was actually super simple

```ts
  const transposed = series.inflate(row => {
    return {
      ...(new Series(row).toObject(
        c => c.month,
        c => c,
      )),
    }
  })

```

**Comment by ashleydavis** [comment]
Cool, thanks for submitting that example.

**Comment by ashleydavis** [comment]
Going to close this now. I'd like to implement a DF function that does this but I'd probably need an example of how this is done in Pandas before I do that. If you can find such an example please reopen this ticket and attach the link.

**Comment by scottmcdonnell** [comment]
I have been trying the suggested solution and cannot get it to work. @tonyxiao what is the example series you are working with? 

I have this:
```typescript
const df = new DataFrame([
  {"week":"week-04","name":"Chris","value":31},
  {"week":"week-05","name":"Chris","value":6.8},
  {"week":"week-06","name":"Chris","value":67},
  {"week":"week-04","name":"David","value":31.5},
  {"week":"week-05","name":"David","value":5.67},
  {"week":"week-06","name":"David","value":723.1},
  {"week":"week-05","name":"Bob","value":5.5},
  {"week":"week-06","name":"Bob","value":65},
])
```
in pandas you can do a pivot like
```python
pivot = df.pivot_table(index='week', columns=['name'], values='value', aggfunc=sum, fill_value=0).T
```
which gives you 
| name              | week-04  | week-05  | week-06 |
| ------------- |-----------| ----------|----------|
| Chris	         | 31             | 	6.8         |   67        
| David	         | 31.5          |	5.67       | 723.1	|
| Bob                 | 0              |   5.5	      | 65            |

Is this possible with the data-forge pivot or transpose?

**Comment by ashleydavis** [comment]
There's documentation here for what you can do with the pivot function:

https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#pivot

There is no transpose function in DF yet, but it wouldn't be difficult to implement if you'd like to have a go?

**Comment by scottmcdonnell** [comment]
thanks @ashleydavis - I did try that but couldn't get the pivot working. Im new to data-forge so it could be just user error. I ended up doing it in lodash for the moment.

**Comment by ashleydavis** [comment]
Ok no worries. Could you share with me the code that does this using lodash?
