### ISSUE TITLE
include a ES Module build

### ISSUE THREAD

**Issue by marcosfede** [data-forge/data-forge-ts#33]
Please include a ES Module version of the package so users using bundlers like webpack can benefit from it and get features like tree-shaking, etc.
Right now the package size is quite [high](https://bundlephobia.com/result?p=data-forge@1.6.7)

**Comment by ashleydavis** [comment]
I'm not sure exactly what you mean, this library already works with webpack.

**Comment by ashleydavis** [comment]
In the future I'm planning to eliminate the two largest dependencies. That will half the size of this package, but still this is large package because *it does a lot of things*.

**Comment by marcosfede** [comment]
I meant that only a es5 common.js build is included https://unpkg.com/data-forge@1.6.7/build/index.js
You could also include a ES module build so your users will be able to take advantage of things like tree-shaking if they are using bundlers
Examples of packages exporting ES modules: 
https://github.com/ramda/ramda/blob/master/package.json#L48
notice the "module" key value pair in package.json and the build:mjs and build:es scripts
and the `es` folder in the npm package https://unpkg.com/ramda@0.26.1/

**Comment by ashleydavis** [comment]
Ok, thanks for providing some more info. I'll see what I can do.

**Comment by ashleydavis** [comment]
The package is getting smaller!

I've removed the two largest dependencies.

Before:

![image](https://user-images.githubusercontent.com/625126/55617319-2614e700-57d7-11e9-8f95-776373411471.png)

After:

![image](https://user-images.githubusercontent.com/625126/55617343-34fb9980-57d7-11e9-95d5-0b3d9c6f5c99.png)

**Comment by ashleydavis** [comment]
It's even better now:

![image](https://user-images.githubusercontent.com/625126/55618791-b3a60600-57da-11e9-8651-1da234a26474.png)

**Comment by ashleydavis** [comment]
@marcosfede or @laevilgenius if you know how to include an ES module build, please do so and submit a PR.

Thanks

**Comment by laevilgenius** [comment]
Apparently webpack doesn't support `esm` target yet. I've been able to build it with rollup though. Would you be interested in a PR with rollup dependency?

**Comment by ashleydavis** [comment]
Yes please @laevilgenius. If it improves Data-Forge without any negative side effects I definitely want it!

**Comment by ashleydavis** [comment]
@laevilgenius thanks so much for your pull request. Testing now, will publish a new build in the next few days.
