### ISSUE TITLE
getColummns() is not a function

### ISSUE THREAD

**Issue by bailih** [data-forge/data-forge-ts#34]
Here is my code:
var transformedData = await new df.DataFrame(data) //data is an array of JSON objects: [{a:1}, {a:3}...]

console.log(transformedData.getColumnNames()) //print out all column Names 

for (const column in transformedData.getColummns()) { //not a function
    console.log("Column name: ");
    console.log(column.name);

    console.log("Data:");
    console.log(column.series.toArray());
}

This is what i get:
"errorMessage": "transformedData.getColummns is not a function",
"errorType": "TypeError"

Why getColumnNames() works and getColummns() doesn't?

**Comment by ashleydavis** [comment]
That's right, there is no function `getColummns`.

You should try this one instead:  `getColumns`
