### ISSUE TITLE
TypeError: data_forge__WEBPACK_IMPORTED_MODULE_8__.readFileSync is not a function

### ISSUE THREAD

**Issue by amitwats** [data-forge/data-forge-ts#35]
When using `const df=dataForge.readFile('SalesJan2009.csv').parseCSV();` in the render method of a ReactJS class the browser shows an error 

> TypeError: data_forge__WEBPACK_IMPORTED_MODULE_8__.readFileSync is not a function

**Comment by ashleydavis** [comment]
You can't access the file system from a web browser. It's just not possible.

You should try loading your data through a REST API.

**Comment by amitwats** [comment]
@ashleydavis Thanks for the quick turn around. I feel the error message shown should mention this. At the moment it sounds like the function the user typed is wrong. Instead a message like "File Resource inaccessible error" would be more appropriate.

**Comment by ashleydavis** [comment]
I can appreciate your confusion and I do mention several places in my documentation that this is how it works.

In any case I'm not sure how I'd put the error message in there (please suggest a way for me to do that and I'll put it in there for you).

Besides, most web developers already know they can't access the file system from the browser. If that were possible then all sorts of web pages would be stealing data from your computer.
