### ISSUE TITLE
Getting Value by date index doesn't work for newly created date.

### ISSUE THREAD

**Issue by nmattise** [data-forge/data-forge-ts#36]
When a date index is set, whether using .setIndex() or explicitly when setting up a dataframe, the index cannot be used to get a value  using that index.
e.g. [dataframe.test.ts](https://github.com/data-forge/data-forge-ts/blob/27c658cbfea422e341432cea32c4e3002410f3ff/src/test/dataframe.test.ts#L239)
`df.at(moment("2014-04-05").toDate())` will return`undefined` while `df.at(testDate)` will pass the test correctly

**Comment by ashleydavis** [comment]
The test passes, which means it work.

Are you able to submit code that demonstrates the problem?

**Comment by ashleydavis** [comment]
Closing after no response.
