### ISSUE TITLE
toCSV after joinOuter running very slow

### ISSUE THREAD

**Issue by dneagoy** [data-forge/data-forge-ts#39]
Ashley, thanks for your awesome work on everything.  I'm new to JavaScript and I'm not sure if my issue is related to something I'm doing or if there's an issue.

I'm having an issue with writing to CSV after performing an outer join.  I've been able to verify that my data frames are being created.  When I display head as pictured below the process is a little slow, but writing to CSV takes minutes to complete.  I originally thought it wasn't writing, but it does seem to write after some period of time.  Additionally, the script seems to hang and I don't return to the command line.

```
`const exceptDF = cleanRev.joinOuter(cleanSF,
    cleanRev => cleanRev.sfKey,
    cleanSF => cleanSF.sfKey,
    (cleanRev, cleanSF) => {
        return {
            index: cleanRev ? cleanRev.sfKey : cleanSF.sfkey,
            swanKey: cleanRev ? cleanRev.sfKey : undefined,
            sfKey: cleanSF ? cleanSF.sfKey : undefined
        };
    }
);

console.log(exceptDF.head(3).toString());  //this works, but it's slow

exceptDF.asCSV().writeFile('exceptDF.csv');  //this writes the file, but it takes several minutes and I don't return to the command line in the terminal`
```

For reference, I'm loading two csv files to different data frames, doing some manipulation, and then performing the outer join.  Each file has around 4,000 rows and 20 columns.

Thanks for any input.

**Comment by ashleydavis** [comment]
Hi thanks for reporting the issue. 

Data-Forge operates in a 'lazy' fashion. Which means you queue up commands that only execute when necessary. That means in this case when you call 'writeFile' it's actually only doing the join outer command at that time, that's why it is slow at that point.

So it's probably only the call to joinOuter causing the slow down.

Are you able to share a code repository with me so I can investigate the performance of it? That might help me to improve the performance or suggest to you a workound to make it faster at your end.

**Comment by dneagoy** [comment]
I shared the repository over with you.  The data files aren't loaded there, but I can modify and load them if necessary.  Thanks

**Comment by ashleydavis** [comment]
Thanks for the example code. Please put some data in there as well, I want to make sure I'm testing the exact same example as you.

**Comment by dneagoy** [comment]
Ashley, I added a couple of files to the repository.  The data is random to protect personal information, but the file structure and number of rows is identical to the files I'm using.  Thanks for taking a look.

**Comment by ashleydavis** [comment]
Thanks, I've started looking at and updating your example repo.

There's a couple of problems in your code that I'll correct before doing performance testing.

Here's an example misuse of data-forge:

![image](https://user-images.githubusercontent.com/625126/57593460-d916f400-757e-11e9-8196-39b0be63fdb2.png)

Please note that the call to `bake` in that code has no effect. Data-Forge follows a lazy evaluation principle which means that all the functions return a new dataframe and *do not modify* the original.

So to use bake you must assign it to something, for example like this:

```javascript
exceptDF = exceptDF.bake();
```

Please take a look at the commits I'm making to your repo to see the corrections I'm making.

**Comment by ashleydavis** [comment]
Just trying to get the code to run (haven't made any changes yet, besides some setup and performance timing). The call to `bake` is hanging (which isn't good). So I need to work out why it's hanging before I can look at performance. 

Please bear with me and look out for some commits and comments over the next few days.

**Comment by ashleydavis** [comment]
Ok I've pushed a couple of commits to the example repo. I've put some calls to `bake` in places where they can make a difference, I've removed the redundant call to `bake`. I also changed the async `writeFile` call to the sync version `writeFileSync`, that's so that it is included in the performance timing.

I time this  now at 2 seconds. Can you please tell me what timing you get from running it?

**Comment by ashleydavis** [comment]
I've done another commit to show you some more code that is having no effect.

**Comment by ashleydavis** [comment]
I can't find any other easy way to improve performance at the moment. 

I'm going to investigate caching at some point, if that works out it will remove the need to do the calls to `bake`.

**Comment by dneagoy** [comment]
Ashley, 

Sorry for the delay here and thanks very much for your help.  I'm new to JavaScript, but the calls to .bake() make a phenomenal difference in speed.  It seems like that was the main reason for the slowdown.  I'll need to read through the documentation a bit more to get a better understanding of when to use them.  

I see a similar time to what you saw.  Thank you for all the help!

**Comment by ashleydavis** [comment]
Fantastic! Thanks again for logging the feedback.

Please make sure you star this repo!
