### ISSUE TITLE
API Docs down. Trying to figure out groupping and .max

### ISSUE THREAD

**Issue by lgomez** [data-forge/data-forge-ts#4]
Hello,

Just noticed the API docs are down and I haven't been able to figure out how to do two things... Hoping you can provide some guidance. Happy to contribute some examples and documentation once I understand this better.

First, is it possible to group by more than one column? I am trying this:
```javascript
  // ...
  .groupBy(row => [row.coin,row.type])
  // ...
```
And it seems to be working. Is that right?

Then, I want to grab the latest of potentially several values per day so I was trying `.max` like so...
```javascript
var latest = indexed
  .orderBy(row => row.timestamp)
  .groupBy(row => [row.coin,row.type])
  .select(group => ({
    coin: group.first().coin, // I'm assuming this returns the first of the series
    type: group.first().type,
    timestamp: group.select(row => row.timestamp).max(), // <-- this
    value: group.first().value,
  }))
  .withIndex(row => moment.unix(row.timestamp/1000).format('YYYY-MM-DD'))
  .inflate();
```
Sorry to bother with this... I keep trying the docs but :s 

Thank you so much!

**Comment by ashleydavis** [comment]
Just tested the API docs. Seem ok now, not sure why there was a problem.

https://data-forge.github.io/data-forge-ts/

I wouldn't be surprised if you could group by more than one column! But it's not something that I've tested myself.

Your assumption in the comment is correct, the first function returns the first item in a series or dataframe, in this case the first item in the group.

Is your example code not working? Do you have some data that I could try it on?

**Comment by ashleydavis** [comment]
Grouping by multiple columns does indeed work! I've just pushed a new unit test to confirm. Thanks so much for pointing that out!!

**Comment by lgomez** [comment]
Yes. They do work... Perhaps just temporarily down. No worries then. Thank you.

**Comment by ashleydavis** [comment]
No worries. Please be sure to star the repo!

Also I have a book coming out called [Data Wrangling with JavaScript](http://bit.ly/2t2cJu2). Please help me spread the word about it!

**Comment by lgomez** [comment]
I had it already starred and already have your book. :)

Thank you

**Comment by lgomez** [comment]
Are you available for contract work and/or hire?

**Comment by ashleydavis** [comment]
Yeah I can do contract work depending on my availability at any given time. Email me on ashley@codecapers.com.au and we can talk about it.
