### ISSUE TITLE
df.summarize is not a function

### ISSUE THREAD

**Issue by tokensalad** [data-forge/data-forge-ts#41]
I'm looking at df.pivot(), which I have working, and as recommended by the docs, I tried looking at df.summarize() but when I run the code I get TypeError df.summarize is not a function

**Comment by ashleydavis** [comment]
Do you have a code example that shows the problem?

If you can give me a working code example in a GitHub repo or Gist I can help you find the problem.

**Comment by tokensalad** [comment]
`const dataForge = require('data-forge');    

const df = dataForge
    .readFileSync("./data/Political_Example_data.csv")    
    .parseCSV()

// console.log(df.getColumnNames());
const pivotted = df.pivot("Q1", "W8Gender", series => series.count());
console.log(pivotted.toString());

const summary = df.summarize();
console.log(summary);
`
The code is super simple (as above). Pivotted returns the dataframe correctly, but summarize returns the error. I will also see if I can create a repo for you. Also, my colleague and I both have your book and I think it is one of the best technical texts I've read.

**Comment by tokensalad** [comment]
I am closing this as I have done a clean install (previously I was partially using setup form Chapter 9 of the book) and it works. I think there must be a version or code problem with that chapter. I appreciate your response nevertheless.

**Comment by ashleydavis** [comment]
Hey I'm glad you solved it and thanks for your kind words about my book.  I'm writing a new book you might be interested in, you can read about it on my blog: http://www.the-data-wrangler.com/bootstrapping-microservices/

Also follow me on Twitter for updates: https://twitter.com/ashleydavis75
