### ISSUE TITLE
JSON5 file / JSON object support

### ISSUE THREAD

**Issue by Berkmann18** [data-forge/data-forge-ts#42]
Would it be possible for this package to support `.json5` files?
I'm trying to use DF on a JSON5 file but even tho I already have a module that turns that file to a JSON object, there's no way for me to use this package to read either the file or read from the object.
Sticking to JSON isn't an option (as comments are needed).

A workaround would be to save the JSON object to a JSON file and read it again but I'm trying to minimise I/O operations and resources used, so it's not a good option.

**Comment by ashleydavis** [comment]
Hey json5 looks pretty cool, thanks for bringing it to my attention. 

I'm pretty maxed out right now with a bunch of projects so I wouldn't have time to add this, although I think it would be a good addition.

I'd be happy for you to add support if it's useful to you.
