### ISSUE TITLE
Data Forge Notebooks "Cannot find module 'data-forge'"

### ISSUE THREAD

**Issue by MayaGans** [data-forge/data-forge-ts#46]
I recently updated notebook versions and now when I try to load the data-forge library using

```
const dataForge = require('data-forge')
```

I get the Error:

```
Cannot find module 'data-forge'
at wrapperFn (1:14)
at <anonymous> (18:10)
```

I also tried using `data-forge-fs`.... am I missing something? 

Thanks!

**Comment by ashleydavis** [comment]
That's strange, I just tried it and it seems ok. 

We should talk about it in the Data-Forge Notebook Slack channel. I've sent you an invite.
