### ISSUE TITLE
Is there a seperator option?

### ISSUE THREAD

**Issue by visualcookie** [data-forge/data-forge-ts#47]
Hey.

I'm currently struggling to aggregate my data right. I got the following example data in my CSV file (abstracted file):

```
10 | 20190404141501 | 2,display_name:server@coolbox,vcpus:1,ram:8096 |
```

Now when reading and working with the Data from that file, the third column gets seperated aswell, since `data-forge` thinks, that `,` is also a seperator. Is there an option, where I can set the seperator, that's used in the file? I haven't found anything in the Guide or the API Documentation.

**Comment by ashleydavis** [comment]
It should be possible.

Under the hood DF uses PapaParse which has the option to set the delimiter:
https://www.papaparse.com/docs#config

There's no official option in DF but the 'csv config' object is passed through to PapaParse so you should be able to do this:

```
const dataFrame = dataForge.fromCSV(csvData, { delimiter: "|" });
````

Or this:
```
const dataFrame = await dataForge.readFile(filePath).parseCSV({ delimiter: "|" });
```

Cheers for the feedback! Make sure you star this repo :)

**Comment by visualcookie** [comment]
@ashleydavis Thanks. Tried it now on the `parseCSV` function, but appearently `delimiter` isn't typed in TypeScript which results in my script not being executed.

Getting the following:
```
Argument of type '{ delimiter: string; columnNames: string[]; }' is not assignable to parameter of type 'ICSVOptions'.
  Object literal may only specify known properties, and 'delimiter' does not exist in type 'ICSVOptions'.

23     delimiter: '|',
       ~~~~~~~~~~~~~~
```

**Comment by ashleydavis** [comment]
Ok try this work around: 

```
const dataFrame = dataForge.fromCSV(csvData, { delimiter: "|" } as any);
```

Or: 

```
const dataFrame = await dataForge.readFile(filePath).parseCSV({ delimiter: "|" } as any);
```

Note the use of *as any*.

If this works for you we can look at getting it officially added.

**Comment by visualcookie** [comment]
@ashleydavis Yeah, works like a charm. TypeScript is blaming the `any` type now, but that's okay for now. 👍

**Comment by ashleydavis** [comment]
Cool.

You would like to be a contributor to Data-Forge and add official support for the 'delimiter' option?

**Comment by visualcookie** [comment]
Already tried to do it here: https://github.com/visualcookie/data-forge-ts/commit/6780a506969514b90a7aa1c90e3071b3e2f49491

Appearently didn't work. Don't know why. 😢

**Comment by ashleydavis** [comment]
You might be on the right track, but I can't tell because you have committed so many cosmetic changes to the code.

It looks like you have some kind of automated code reformatting happening there.  Please figure out what that is, turn it off and try again.

When I look at the commit it says:

Showing 1 file with 202 additions and 159 deletions.

That's a huge number of changes! I imagine that you don't didn't mean to make all those changes!

**Comment by visualcookie** [comment]
Yeah, you're right. Seems that some extension in my VSCode setup is interfering. Will have it checked immediately.

**Comment by ashleydavis** [comment]
Cool. Thanks for trying! It'll be awesome if you can contribute this feature.

**Comment by visualcookie** [comment]
@ashleydavis Hey. Tried to do it, but the issue is, that my VSCode has a different style guide than yours. Do you have a `.editorconfig` file for me, so the code style matches?

**Comment by ashleydavis** [comment]
It has a different style guide? Can't you just disable automatic modifications to the code? 

As far as I know VSCode doesn't even do this by default. It's never done it for me for any project that I've worked on.

You must have a separate plugin installed that's doing this and in that case I can't see how .editorconfig is going to help.
