### ISSUE TITLE
Cannot access the implementation examples in http://blogs.geniuscode.net

### ISSUE THREAD

**Issue by alvi1987** [data-forge/data-forge-ts#50]
Hi,
I cannot access the implementation examples referred in the API docs. Is it down?

**Comment by ashleydavis** [comment]
Where did you a see a link to http://blogs.geniuscode.net?

I have no idea that that is.

**Comment by alvi1987** [comment]
Take a look at this file
```
https://github.com/data-forge/data-forge-ts/blob/5ad062aa80dce55a5185817b783325cda3259132/src/test/series.join.test.ts
```

**Comment by alvi1987** [comment]
Ah, sorry, I think the examples were provided in the archived repository of data-forge-js api docs. My bad. closing the issue.
