### ISSUE TITLE
Pandas melt() alternative?

### ISSUE THREAD

**Issue by empz** [data-forge/data-forge-ts#59]
I'm trying to find how to do something like the pandas melt() method.

Basically I need to go from this:

```
|Date|A|B|C|D|E |
|----|-|-|-|-|--|
|2005|1|2|3|4|50|
|2006|6|7|8|9|10|
```

Doing something like:
`df.melt("Date", { varName: "X", valueName: "Val" })`

And get this:
```
|Date|X|Val|
|----|-|---|
|2005|A|1  |
|2005|B|2  |
|2005|C|3  |
etc 
|2006|A|6  |
etc
|2006|E|10 |
```

**Comment by ashleydavis** [comment]
Thanks for your feedback.

It actually sounds a bit like pivot.

Can you find me a blog post or documentation that describes how it works? That will help me understand it.

**Comment by eparizzi** [comment]
Pivot is the other way around. This is usually called "unpivot".
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.melt.html

These two methods are very common methods in any dataset manipulation language. Here's the definition of both on SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15

**Comment by ashleydavis** [comment]
Melt function has been added in version 1.8.9 thanks to @karishnu .

I haven't published documentation yet, so I'll keep this issue open for the moment.
