### ISSUE TITLE
Updating package.json dependencies (security)

### ISSUE THREAD

**Issue by torenken** [data-forge/data-forge-ts#72]
Since yesterday it is a security incident (https://npmjs.com/advisories/1515). Can you please update the project dependencies of papaparse.

**Comment by ashleydavis** [comment]
Please feel free to submit a PR, otherwise I'll get to it as soon as I can.

**Comment by eparizzi** [comment]
PR submitted.

https://github.com/data-forge/data-forge-ts/pull/78
