### ISSUE TITLE
How to do bulk transformation?

### ISSUE THREAD

**Issue by baocancode** [data-forge/data-forge-ts#76]
Hi,

Is there a way to group multiple transformation steps together so that I can share it between multiple places? For example, if I want to get the n-th row of a data frame, I would use the following 3 steps: `.skip(n-1).take(1).first()` (by the way, is it the best approach?).

To reuse it, I can make a function like: `getAt = (df: IDataFrame, n: number) => df.skip(n-1).take(1).first()` but need to use a temporary variable, like:

```
const df = new DataFrame(...)
const row = getAt(df, n)
```

Would be nice if can apply a transformation function to a data frame directly, like:

```
const row = new DataFrame(...)
  .apply((df) => getAt(df, n))
```

The `apply` method can be implemented as simple as:

```
apply (transformer) {
  return transformer(this)
}
```

I'm not familiar with Pandas to know whether it has something similar.

Regards

**Comment by ashleydavis** [comment]
You can share transformation steps (or any code) by writing a JavaScript function.

There's multiple ways to do transformation.

Have you ready the guide: https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md
