### ISSUE TITLE
pandas.read_excel equivalent or recommended way to work with Excel?

### ISSUE THREAD

**Issue by fnick851** [data-forge/data-forge-ts#77]
Thanks for creating this library!

I quite often need to work with data saved as Excel file (.xlsx). Is there an equivalent for [pandas.read_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)?  

If not, what is the recommended way to parse and work with Excel files?

**Comment by ashleydavis** [comment]
Hey thanks for your feedback.

You can load CSV files. So export your Excel file as CSV.

You can see an example here: https://data-forge-notebook.github.io/data-forge-cheat-sheet/

There's no function to load Excel directly, although I'd love to have that in Data-Forge if you'd like to contribute?

**Comment by fnick851** [comment]
@ashleydavis Thank you! 
Some Excel has composite headers e.g. multiple rows of headers etc. But I guess that could be converted to JSON first too. Or I could use some other library to parse Excel first. 

I would love to contribute and make an Excel loader if I figured out how to do that. I haven't had any experiences with writing libraries like this but it is interesting.

**Comment by ashleydavis** [comment]
If you'd like to experiment with doing this please feel to create your own GitHub repo, make a prototype for the `readExcel` function then we could work together to try and figure out the best way to fit it into Data-Forge properly.

**Comment by fnick851** [comment]
@ashleydavis I ended up using https://github.com/Siemienik/xlsx-import to read Excel files which I think provides a quite intuitive API. (It uses https://github.com/exceljs/exceljs underneath, and is written in TypeScript too.)
So maybe data-forge could wrap this if it wants to provide an Excel reader out of the box? (But there are already quite a few options in the JS world for parsing Excel anyways.)

**Comment by ashleydavis** [comment]
That sounds awesome, thanks for sharing. Please let me know how you go with it.
