### ISSUE TITLE
Reshape table using Pivot

### ISSUE THREAD

**Issue by Grimi94** [data-forge/data-forge-ts#81]
Hello I'm trying to reshape a table like the following example from: [pydata Pandas Reshaping](https://pandas.pydata.org/docs/user_guide/reshaping.html)
<img src="https://pandas.pydata.org/docs/_images/reshaping_pivot.png" width="550">
So far I have tried with the following code:
```javascript
df = new dataForge.DataFrame({columns: {"foo": ["one", "one", "one", "two", "two","two"],
                                        "bar": ["a", "b", "c", "a", "b", "c"],
                                        "baz": [1, 2, 3, 4, 5, 6]}})
df = df.setIndex("foo").dropSeries("foo").bake()
df.pivot("bar", "baz", dataForge.Series.sum).toString()
```
which yields 
```
__index__  bar  baz
---------  ---  ---
0          a    5  
1          b    7  
2          c    9  
```
But it seems to just ignore the index and group by the "baz" column. I have tried different variations but still I cant get it to work.

How can I achieve what is shown on the picture above?

**Comment by ashleydavis** [comment]
Have you read the guide for the pivot function?

https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#pivot

Try reading that first and you might find what you are looking for.

Otherwise I'll come back and have a look next week.

**Comment by Grimi94** [comment]
Thanks for the suggestion, I read the guide for the pivot function. What I'm trying to achieve is to group a column and then use that column as the header row while reshaping the dataframe. If we go back to the example on the image it is using the "foo" column as an index and then grouping and using the "bar" column as the new header on the output. The following is the result im trying to get:
```
__index__   a    b   c
---------  ---  --- ---
one         1    2   3  
two         4    5   6  
```

**Comment by ashleydavis** [comment]
I'm sorry after reading the documentation for Pandas [pivot](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html) and [pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) I think that the Data-Forge pivot function works like pivot_table rather than pivot.

What do you ultimately hope to do with this. If you could explain the problem you are trying to solve I can probably find another way to help you achieve it.

**Comment by zyzhu** [comment]
I am exploring the same problem today using data-forge. I think this chapter explains well the similar scenarios and rationales of pivot in R's tidyverse
https://r4ds.had.co.nz/tidy-data.html

**Comment by ashleydavis** [comment]
Thanks for the info. I'm hoping to spend more time this year expanding Data-Forge, so stay tuned.

Although if you'd like to contribute to improving this code library, please do!

**Comment by ashleydavis** [comment]
Sorry, never got back to this issue.

If anyone else is able to contribute a PR for this I'll be open to reopen this issue.

**Comment by mvogelito** [comment]
I'm just coming across this and thought I would add my solution for anyone who stumbles on this in the future.  I just started looking at data-forge, so I'm not sure if this is the most efficient way.  I also don't know Typescript or github/PRs, otherwise I would contribute.

The missing link is a function like pandas `unstack()` (opposite of `melt()`), which is baked into pandas `pivot_table()` (and `pivot()` -- the only difference between the two is that `pivot()` doesn't do aggregation like `pivot_table()` does).  
So:  pandas `pivot_table()`   roughly equals   data-forge's `pivot()` plus this `unstack()` below.

Since I don't think there are multiIndexes in data-forge (right?), this is a little more awkward than it might be.  But below should work (at least for simple cases like below).

```
function pivotAndUnstack(dfIn, rowsName, colsName, valsName, valAggFunc) {
    // Return a new df that is like pandas "pivot_table" output.
    // Pandas equivalent syntax:
    //      df.pivot_table(index=['Date'], columns=['Category'],   \
    //          values='Value', aggfunc=valAggFunc).reset_index()
    // Differences: 
    //  * This function does not make any changes to the index, but instead
    //      keeps that data in the first column.
    //  * This function does not handle multi-levels of pivot/multiIndex.
    //
    // Input:
    //  * 'rowsName' [string] is the name of the column in dfIn whose unique values
    //      will become the values in the first column of dfOut.
    //  * 'colsName' [string] is the name of the column in dfIn whose unique values
    //      will become the column names (along with rowsName) of dfOut.
    //  * 'valsName' [string] is the name of the column in dfIn that will be aggregated
    //      to form the "field" of dfOut, corresponding to row/col name pair.
    //  * 'valAggFunc' [function] is the aggregator acting on values in 'valsName' column.
    // Output:
    //  The df, as described above.
        
    const dfPivoted = dfIn.pivot([rowsName, colsName], valsName, valAggFunc);
    let dfOut = unstack(dfPivoted, rowsName, colsName, valsName);
    return dfOut;
}

function unstack(dfPivoted, rowsName, colsName, valsName) { 
    // See description in pivotAndUnstack().
    // Note that unstack() is basically the opposite of melt().  If we do:
    //      let dfIn = ... some df
    //   => let dfPivoted = dfIn.pivot([rowsName, colsName], valsName, valAggFunc);
    //      let dfUnstacked = unstack(dfPivoted, rowsName, colsName, valsName);
    //      let uniqueCols = dfPivoted.deflate(row => row[colsName]).distinct().toArray();
    //   => let dfMelted = dfUnstacked.melt('Date', uniqueCols);
    // Then dfPivoted should be the same as dfMelted.

    let unstackedData = [];
    let prevRowsName, newRow;

    // Make sure all entries in colsName are present on first row,
    //   otherwise any missing entries seem to be excluded?
    let uniqueCols = dfPivoted.deflate(row => row[colsName]).distinct();
    let newRowStarter = {[rowsName]: undefined};
    uniqueCols.forEach(colName => {
        newRowStarter[colName] = undefined;
    });

    dfPivoted.forEach(row => {
        // Keep filling the "field" until we have a new value in rowsName
        if (row[rowsName] !== prevRowsName) {
            prevRowsName = row[rowsName];
            newRow = {...newRowStarter };
            newRow[rowsName] = row[rowsName];

            unstackedData.push(newRow);
        }
        newRow[row[colsName]] = row[valsName];
    });

    let unstackedDf = new dataForge.DataFrame({ values: unstackedData });
    return unstackedDf;
}
```

Example usage. The input:
```
const dfIn = new dataForge.DataFrame({
    values: [
        { 'Date': '2025-03-11', 'Category': 'A', 'Value': 10 },
        { 'Date': '2025-03-11', 'Category': 'B', 'Value': 15 },
        { 'Date': '2025-03-12', 'Category': 'A', 'Value': 20 },
        { 'Date': '2025-03-11', 'Category': 'B', 'Value': 25 },
        { 'Date': '2025-03-12', 'Category': 'B', 'Value': 30 },
        { 'Date': '2025-03-12', 'Category': 'C', 'Value': 35 },
        { 'Date': '2025-03-12', 'Category': 'A', 'Value': 40 },
        { 'Date': '2025-03-12', 'Category': 'C', 'Value': 45 },
    ]
});
display(dfIn.toString());

// Gives dfIn:
__index__  Date        Category  Value
---------  ----------  --------  -----
0          2025-03-11  A         10   
1          2025-03-11  B         15   
2          2025-03-12  A         20   
3          2025-03-11  B         25   
4          2025-03-12  B         30   
5          2025-03-12  C         35   
6          2025-03-12  A         40   
7          2025-03-12  C         45   
``` 
And using the function to get ouput:
```
let dfOut = pivotAndUnstack(dfIn, 'Date', 'Category', 'Value', (values) => values.sum());
display(dfOut.toString());

// Gives desired output:
__index__  Date        A   B   C 
---------  ----------  --  --  --
0          2025-03-11  10  40    
1          2025-03-12  60  30  80
```

**Comment by ashleydavis** [comment]
Thanks so much for your input @mvogelito. If you'd like to contribute some code please let me know.
