### ISSUE TITLE
DataFrame treats column names as case insensitive

### ISSUE THREAD

**Issue by mayanktanwar5** [data-forge/data-forge-ts#85]
Hi, 

Class Dataframe **initColumnNames** function is case insensitive and convert all the column names to lower case and consider them as duplicates, for our use case we need column name to be case sensitive.

`const df = new dataForge.DataFrame({
    columnNames: ["Col", "col", "Column"],
    rows: [
        [1, 'hello'],
        [5, 'computer'],
        [10, 'good day']
    ]
});`

which gives 
`columns : [ "col1", "col2", "column"]
`
can we add toggle that add setCaseSensitivity() setting in the library.

**Comment by ashleydavis** [comment]
Fixed by #86 .
