### ISSUE TITLE
Streaming on rows as they are parsed

### ISSUE THREAD

**Issue by vallettea** [data-forge/data-forge-ts#9]
Hello, 

thanks for this awesome project that hopefully will help me to dump python.

I'm using it to read a csv file, cleaning the data and inserting into postgres.
To deal with huge csv file, I'd like to pipe the rows as they are parsed into postgres without having to keep the full dataframe into memory. 
How would you do that ? Using through ?
Thanks

**Comment by ashleydavis** [comment]
Hi, thanks for your encouragement.

Unfortunately Data-Forge doesn't yet support streaming files. I didn't experiment with it a couple of months ago but decided it was too difficult to implement for the moment.  I'll try again sometime in the future.

One way that you could deal with this though is to process the CSV file in chunks where each chunk contains multiple rows. You could then load a chunk at a time into a DataFrame for processing.

Let me know if that helps?

**Comment by vallettea** [comment]
thanks
that's what I did but it's not as clean as a real pipeline.

**Comment by ashleydavis** [comment]
Cheers, hopefully will get it fixed in the future.

Please be sure to star the repo!

**Comment by ashleydavis** [comment]
Hey Alexandre,

Just wondering if you've seen my new library yet?

It's called Data-Forge Plot and integrates plotting/charting with Data-Forge.

Please check out [my blog post on it](http://www.the-data-wrangler.com/introducing-data-forge-plot/).

It's early days yet, but I'm trying to collect feedback on it.

**Comment by vallettea** [comment]
Thanks for the link.
You are really doing a beautiful job.
I really enjoy the export to the web or to node capabilities.
My only critic would be that you should push more on the functionalities offered by nodejs that are cumbersome in python and that is streaming ! (for example streaming to a plot for real time viz etc).

well done, stared both you projects.

**Comment by ashleydavis** [comment]
Yes  I do believe streaming is important. It will come in time... but it's a big feature and it's hard to find time at the moment.

Thanks for the star!

**Comment by tannerntannern** [comment]
Has this been reconsidered?  Looks like [papaparse supports streaming](https://www.papaparse.com/#stream), which might make the feature easier?

**Comment by ashleydavis** [comment]
This is definitely something I'd like to have in there. @tannerntannern would you like to have a go at it?

**Comment by tannerntannern** [comment]
@ashleydavis, I would love to but I've got lots of projects competing for my time at the moment.  Might be quite some time before I'd be able to get around to it.  Mostly curious if this was already in the works or if I missed something in the docs that makes streaming possible.

**Comment by ashleydavis** [comment]
Data-Forge was built early on (first commit was almost 5 years ago!) to support streaming data.

It's architecture is built on lazy initialisation and iterators. Iterators mean that every pass through iteration of rows is a new opportunity to load data. 

So Data-Forge is almost ready for this feature. Although I suspect there might be some issues dealing with asynchronous file loading.... if we have to change the DF interface we might have to make it version 2!
