### ISSUE TITLE
Restore columns after window

### ISSUE THREAD

**Issue by b0lle** [data-forge/data-forge-ts#91]
Hey Guys,

I have a dataframe with a time series. To resample the dataframe I choosed to use the window function.
Then I calculated that I need **180** Windows, to resample the timeseries by 1 minute.

First question
----------------
after applying the window function I got only **62** windows but I expected 180.

Second question
------------------
The resulting Dataframe now looks like:
```
__index__  __value__      
---------  ---------------
0          [object Object]
1          [object Object]
2          [object Object]
```
How can I restore the columns so that the dataframe looks like
```
utc_timestamp  stop_cnt  prod_cnt
---------  ---------------
0         1       10
1         0       11
2         0       12
```

My code looks like:

// window definition
timestamp_min = moment(df.getSeries('utc_timestamp').min())
timestamp_max = moment(df.getSeries('utc_timestamp').max())
timerange_in_seconds = timestamp_max.diff(timestamp_min, 'seconds')
windows = timerange_in_seconds / 60

```
const weeklySales = sequenceWithoutGaps.window(windows).select(
    window => {return {
        utc_timestamp: window.getSeries('utc_timestamp').min(),
        stop_cnt  : window.getSeries('stop_cnt').sum(),
        prod_cnt: window.getSeries('prod_cnt').sum()
    }}
    )
```

Thanks for any help!

**Comment by ashleydavis** [comment]
Window always returns a series and not a dataframe, but you can turn a series into a dataframe through the "inflate" function as follows:

```javascript
const weeklySales = sequenceWithoutGaps.window(windows)
	.select(window => {return {
		utc_timestamp: window.getSeries('utc_timestamp').min(),
		stop_cnt  : window.getSeries('stop_cnt').sum(),
		prod_cnt: window.getSeries('prod_cnt').sum()
	}})
	.inflate();
```

**Comment by ashleydavis** [comment]
However you will find that you are stripping the index. That might be ok, but if you'd like to preserve the index you should return the index (first, last or mid-window) from your window function and the restore the index from that, here's the example from the guide:

```javascript
const salesData = // ... series containing amount of sales for each day ...

const weeklySales = salesData.window(7) // Group into lots of 7 (for 7 days).
    .select(window => {
        return [                    // Return index and value.
            window.lastIndex(),     // Week ending.
            window.sum()            // Total the amount sold during the week.
        ]; 
    })
    .withIndex(pair => pair[0]) // Promote index.
    .select(pair => pair[1]); // Restore values.
```

See [the guide](https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md#groups-and-windows) for more of an explanation.

**Comment by ashleydavis** [comment]
I'm not sure what you mean by the first question, but I'm happy to comment on working example code if you can put something in GitHub and share it with me.

Please open a new issue for that.
